
  CREATE TABLE "YSPOS23"."AQ$_DOC_SYS_ID_Q_TBL_I"
   (	"SUBSCRIBER#" NUMBER,
	"NAME" VARCHAR2(30),
	"QUEUE#" NUMBER,
	"MSG_PRIORITY" NUMBER,
	"MSG_ENQ_TIME" TIMESTAMP (6),
	"MSG_STEP_NO" NUMBER,
	"MSG_CHAIN_NO" NUMBER,
	"MSG_LOCAL_ORDER_NO" NUMBER,
	"MSGID" RAW(16),
	"HINT" ROWID,
	"SPARE" RAW(16),
	 CONSTRAINT "SYS_IOT_TOP_166548" PRIMARY KEY ("SUBSCRIBER#", "NAME", "QUEUE#", "MSG_PRIORITY", "MSG_ENQ_TIME", "MSG_STEP_NO", "MSG_CHAIN_NO", "MSG_LOCAL_ORDER_NO", "MSGID") ENABLE
   ) USAGE QUEUE ORGANIZATION INDEX NOCOMPRESS ;

