
  CREATE TABLE "YSPOS23"."AQ$_DOC_SYS_ID_Q_TBL_H"
   (	"MSGID" RAW(16),
	"SUBSCRIBER#" NUMBER,
	"NAME" VARCHAR2(30),
	"ADDRESS#" NUMBER,
	"DEQUEUE_TIME" TIMESTAMP (6),
	"TRANSACTION_ID" VARCHAR2(30),
	"DEQUEUE_USER" VARCHAR2(30),
	"PROPAGATED_MSGID" RAW(16),
	"RETRY_COUNT" NUMBER,
	"HINT" ROWID,
	"SPARE" RAW(16),
	 CONSTRAINT "SYS_IOT_TOP_166542" PRIMARY KEY ("MSGID", "SUBSCRIBER#", "NAME", "ADDRESS#") ENABLE
   ) USAGE QUEUE ORGANIZATION INDEX NOCOMPRESS ;

