
  CREATE TABLE "YSPOS23"."AQ$_DOC_SYS_ID_Q_TBL_L"
   (	"MSGID" RAW(16),
	"SUBSCRIBER#" NUMBER,
	"NAME" VARCHAR2(30),
	"ADDRESS#" NUMBER,
	"DEQUEUE_TIME" TIMESTAMP (6) WITH TIME ZONE,
	"TRANSACTION_ID" VARCHAR2(30),
	"DEQUEUE_USER" VARCHAR2(30),
	"FLAGS" RAW(1)
   ) USAGE QUEUE ;

