
  CREATE TABLE "YSPOS23"."AQ$_DOC_SYS_ID_Q_TBL_T"
   (	"NEXT_DATE" TIMESTAMP (6),
	"TXN_ID" VARCHAR2(30),
	"MSGID" RAW(16),
	"ACTION" NUMBER,
	 CONSTRAINT "SYS_IOT_TOP_166540" PRIMARY KEY ("NEXT_DATE", "TXN_ID", "MSGID") ENABLE
   ) USAGE QUEUE ORGANIZATION INDEX NOCOMPRESS ;

