
  CREATE TABLE "YSPOS23"."AQ$_DOC_SYS_ID_Q_TBL_G"
   (	"MSGID" RAW(16),
	"SUBSCRIBER#" NUMBER,
	"NAME" VARCHAR2(30),
	"ADDRESS#" NUMBER,
	"SIGN" "SYS"."AQ$_SIG_PROP" ,
	"DBS_SIGN" "SYS"."AQ$_SIG_PROP" ,
	 CONSTRAINT "SYS_IOT_TOP_166545" PRIMARY KEY ("MSGID", "SUBSCRIBER#", "NAME", "ADDRESS#") ENABLE
   ) USAGE QUEUE ORGANIZATION INDEX NOCOMPRESS	INCLUDING "SIGN" OVERFLOW;

