
  CREATE TABLE "YSPOS23"."IAS_DEPOSIT_CURRENCY_DTL"
   (	"DOC_NO" NUMBER(38,0),
	"DOC_SER" NUMBER(38,0),
	"A_CY" VARCHAR2(7 CHAR),
	"EX_RATE" NUMBER,
	"CUR_VALUE" NUMBER,
	"CUR_NUMBER" NUMBER,
	"AD_U_ID" NUMBER(5,0),
	"AD_DATE" DATE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0),
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0),
	 CONSTRAINT "IAS_DEPOSIT_CURRENCY_DTL_PK" PRIMARY KEY ("DOC_SER", "A_CY", "CUR_VALUE")
  USING INDEX  ENABLE
   ) ;

