
  CREATE TABLE "YSPOS23"."IAS_POS_CASHIER_FIN_TRUST"
   (	"U_ID" NUMBER(5,0),
	"A_CY" VARCHAR2(7 CHAR),
	"AMT" NUMBER(38,0),
	"PAY_AMT" NUMBER(38,0),
	"AD_U_ID" NUMBER(5,0),
	"AD_DATE" DATE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"UP_CNT" NUMBER(10,0),
	"PR_REP" NUMBER(6,0),
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0),
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0),
	 CONSTRAINT "IAS_POS_CASH_FIN_TRUST_PK" PRIMARY KEY ("U_ID", "A_CY")
  USING INDEX  ENABLE
   ) ;

