
  CREATE TABLE "YSPOS23"."IAS_POS_RT_BILL_DTL_AUD_TMP"
   (	"RT_BILL_NO" NUMBER,
	"MACHINE_NO" NUMBER(5,0),
	"I_CODE" VARCHAR2(30 CHAR),
	"P_SIZE" NUMBER,
	"ITM_UNT" VARCHAR2(10 CHAR),
	"I_QTY" NUMBER,
	"BARCODE" VARCHAR2(100 CHAR),
	"RCRD_NO" NUMBER,
	"BRN_NO" NUMBER(6,0),
	"BRN_YEAR" NUMBER(4,0),
	"CMP_NO" NUMBER(3,0),
	"BRN_USR" NUMBER(3,0)
   ) ;

