
  CREATE GLOBAL TEMPORARY TABLE "YSPOS23"."IAS_POS_MINUS_STK_QTY_TMP"
   (	"I_CODE" VARCHAR2(30 CHAR),
	"W_CODE" NUMBER(10,0),
	"EXPIRE_DATE" DATE,
	"BATCH_NO" VARCHAR2(30 CHAR),
	"P_QTY" NUMBER,
	"AVL_QTY" NUMBER,
	"BRN_NO" NUMBER(6,0)
   ) ON COMMIT DELETE ROWS ;

