
  CREATE GLOBAL TEMPORARY TABLE "YSPOS23"."IAS_POS_CHNG_BILL_PST_AUTO_TMP"
   (	"BILL_NO" NUMBER,
	"RT_BILL_NO" NUMBER,
	"PAY_AMT" NUMBER,
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0),
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0),
	"BRN_SER" NUMBER(6,0)
   ) ON COMMIT DELETE ROWS ;

