
  CREATE TABLE "YSPOS23"."IAS_INV_RT_BILL_MST"
   (	"DOC_NO" NUMBER(15,0) NOT NULL ENABLE,
	"DOC_SER" NUMBER(38,0),
	"DOC_DATE" DATE,
	"DOC_DESC" VARCHAR2(250 CHAR),
	"REF_NO" VARCHAR2(15 CHAR),
	"POSTED" NUMBER(1,0) DEFAULT 0,
	"PROCESSED" NUMBER(1,0) DEFAULT 0,
	"MACHINE_NO" NUMBER,
	"W_CODE" NUMBER(10,0),
	"AD_U_ID" NUMBER(5,0),
	"AD_DATE" DATE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"UP_CNT" NUMBER(10,0),
	"PR_REP" NUMBER(6,0),
	"AD_TRMNL_NM" VARCHAR2(50 CHAR),
	"UP_TRMNL_NM" VARCHAR2(50 CHAR),
	"CMP_NO" NUMBER(3,0) NOT NULL ENABLE,
	"BRN_NO" NUMBER(6,0) NOT NULL ENABLE,
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0) NOT NULL ENABLE,
	"DOC_TIME" VARCHAR2(10 CHAR),
	"CASHIER_NO" NUMBER(5,0)
   ) ;

