
  CREATE TABLE "YSPOS23"."IAS_POS_BILL_CPN_MOVMNT"
   (	"DOC_TYP" NUMBER(2,0) NOT NULL ENABLE,
	"DOC_NO" NUMBER(38,0) NOT NULL ENABLE,
	"DOC_DATE" DATE,
	"CPN_NO" VARCHAR2(60 CHAR) NOT NULL ENABLE,
	"CPN_AMT" NUMBER,
	"QT_PRM_NO" NUMBER(15,0),
	"QT_PRM_SER" NUMBER(38,0),
	"QT_PRM_RCRD_NO" NUMBER(10,0),
	 CONSTRAINT "IAS_POS_BILL_CPN_PK" PRIMARY KEY ("DOC_TYP", "DOC_NO", "CPN_NO")
  USING INDEX  ENABLE
   ) ;

