
  CREATE TABLE "YSPOS23"."IAS_POS_SERVER_SNCRNZ_DATA"
   (	"SERVER_NO" NUMBER NOT NULL ENABLE,
	"SNCRNZ_TIME" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"SNCRNZ_JOB_TYP" NUMBER(2,0),
	"SNCRNZ_SRVR_TYP" NUMBER(1,0) DEFAULT 1,
	"AD_U_ID" NUMBER(5,0),
	"AD_DATE" DATE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"AD_TRMNL_NM" VARCHAR2(50 CHAR),
	"UP_TRMNL_NM" VARCHAR2(50 CHAR),
	 CONSTRAINT "POS_SERVER_SNCRNZ_DATA_PK" PRIMARY KEY ("SERVER_NO", "SNCRNZ_TIME")
  USING INDEX  ENABLE
   ) ;

