
  CREATE TABLE "YSPOS23"."IAS_TRACE_LGN_NOTE"
   (	"NT_NO" NUMBER(15,0),
	"NT_DIS" NUMBER(1,0),
	"NT_DIS_U_ID" NUMBER(5,0),
	"NT_DIS_DATE" DATE,
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0),
	"BRN_USR" NUMBER(3,0),
	"BRN_YEAR" NUMBER(4,0),
	"TRMNL_NAME" VARCHAR2(100 CHAR),
	"PR_REP" NUMBER(10,0),
	"UP_CNT" NUMBER(10,0),
	"AD_TRMNL_NM" VARCHAR2(50 CHAR),
	"UP_TRMNL_NM" VARCHAR2(50 CHAR)
   ) ;

