
  CREATE TABLE "YSPOS23"."IAS_POS_KEY_BRD_GRPS_MST"
   (	"EXTRA_KEYPAD_NO" NUMBER,
	"KGRP_CODE" VARCHAR2(6 CHAR),
	"KGRP_A_NAME" VARCHAR2(100 CHAR),
	"KGRP_E_NAME" VARCHAR2(100 CHAR),
	"AD_U_ID" NUMBER(5,0),
	"AD_DATE" DATE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0),
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0),
	 CONSTRAINT "IAS_PK_KGRPS_MST" PRIMARY KEY ("EXTRA_KEYPAD_NO", "KGRP_CODE")
  USING INDEX  ENABLE,
	 CONSTRAINT "IAS_FK_KGRPS_MST" FOREIGN KEY ("EXTRA_KEYPAD_NO")
	  REFERENCES "YSPOS23"."IAS_POS_EXTRA_KEYPAD" ("EXTRA_KEYPAD_NO") ENABLE
   ) ;

