
  CREATE TABLE "YSPOS23"."IAS_POS_AUD_ITEM"
   (	"BILL_NO" NUMBER(38,0),
	"BILL_DATE" DATE DEFAULT SYSDATE,
	"BILL_TIME" VARCHAR2(10 CHAR),
	"A_CY" VARCHAR2(7 CHAR),
	"BILL_RATE" NUMBER,
	"MACHINE_NO" NUMBER,
	"I_CODE" VARCHAR2(30 CHAR),
	"P_SIZE" NUMBER,
	"ITM_UNT" VARCHAR2(10 CHAR) NOT NULL ENABLE,
	"W_CODE" NUMBER(10,0),
	"I_PRICE" NUMBER,
	"I_QTY" NUMBER,
	"BARCODE" VARCHAR2(100 CHAR),
	"HUNG_BILL" NUMBER(1,0) DEFAULT 0,
	"AUD_U_ID" NUMBER(5,0),
	"AUD_DATE" DATE,
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0),
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0)
   ) ;

