
  CREATE TABLE "YSPOS23"."IAS_POS_BALANCE"
   (	"BALANCE_NO" NUMBER,
	"BALANCE_A_NAME" VARCHAR2(60 CHAR),
	"BALANCE_E_NAME" VARCHAR2(60 CHAR),
	"AD_U_ID" NUMBER(5,0),
	"AD_DATE" DATE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"AD_TRMNL_NM" VARCHAR2(50 CHAR),
	"UP_TRMNL_NM" VARCHAR2(50 CHAR),
	"UP_CNT" NUMBER(10,0),
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0),
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0),
	"IP" VARCHAR2(15 CHAR),
	"BALANCE_TYPE" NUMBER(2,0),
	 CONSTRAINT "IAS_POS_BALANCE_PK" PRIMARY KEY ("BALANCE_NO")
  USING INDEX  ENABLE
   ) ;

