
  CREATE TABLE "YSPOS23"."IAS_DEPOSIT_CREDIT_CARD"
   (	"DOC_NO" NUMBER(38,0),
	"DOC_SER" NUMBER(38,0),
	"CR_CARD_NO" NUMBER(5,0),
	"CR_CARD_AMT" NUMBER,
	"A_CY" VARCHAR2(7 CHAR),
	"EX_RATE" NUMBER,
	"AD_U_ID" NUMBER(5,0),
	"AD_DATE" DATE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0),
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0),
	"BANK_NO" NUMBER(12,0),
	 CONSTRAINT "IAS_DEPOSIT_CREDIT_CARD_PK" PRIMARY KEY ("DOC_SER", "CR_CARD_NO", "A_CY")
  USING INDEX  ENABLE
   ) ;

