
  CREATE TABLE "YSPOS23"."IAS_USR_LGN_HSTRY"
   (	"U_ID" NUMBER(5,0) NOT NULL ENABLE,
	"TRMNL_NM" VARCHAR2(30 CHAR),
	"LGN_TYP" NUMBER(1,0),
	"LGN_OUT_DATE" DATE NOT NULL ENABLE,
	"LNG_NO" NUMBER(3,0),
	"CMP_NO" NUMBER(3,0) NOT NULL ENABLE,
	"BRN_NO" NUMBER(6,0) NOT NULL ENABLE,
	"BRN_YEAR" NUMBER(4,0) NOT NULL ENABLE,
	"BRN_USR" NUMBER(3,0) NOT NULL ENABLE
   ) ;

