
  CREATE TABLE "YSPOS23"."IAS_POS_EXTRA_KEYPAD"
   (	"EXTRA_KEYPAD_NO" NUMBER,
	"AD_U_ID" NUMBER(5,0),
	"AD_DATE" DATE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0),
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0),
	"EXTRA_KEYPAD_A_NAME" VARCHAR2(100 CHAR),
	"EXTRA_KEYPAD_E_NAME" VARCHAR2(100 CHAR),
	 CONSTRAINT "IAS_POS_KEYPADPK" PRIMARY KEY ("EXTRA_KEYPAD_NO")
  USING INDEX  ENABLE
   ) ;

