
  CREATE TABLE "YSPOS23"."IAS_INV_RT_BILL_DTL"
   (	"DOC_NO" NUMBER(15,0) NOT NULL ENABLE,
	"DOC_SER" NUMBER(38,0),
	"I_CODE" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"ITM_UNT" VARCHAR2(10 CHAR),
	"W_CODE" NUMBER(10,0),
	"I_QTY" NUMBER,
	"RT_BILL_QTY" NUMBER,
	"P_SIZE" NUMBER NOT NULL ENABLE,
	"P_QTY" NUMBER,
	"BARCODE" VARCHAR2(100 CHAR),
	"EXPIRE_DATE" DATE NOT NULL ENABLE,
	"BATCH_NO" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"RCRD_NO" NUMBER(10,0),
	"ITEM_DESC" VARCHAR2(250 CHAR),
	"CMP_NO" NUMBER(3,0) NOT NULL ENABLE,
	"BRN_NO" NUMBER(6,0) NOT NULL ENABLE,
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0) NOT NULL ENABLE,
	"UP_CNT" NUMBER(10,0)
   ) ;

