
  CREATE TABLE "YSPOS23"."IAS_EXTRNL_SYS_SYNC_LOG"
   (	"SEQ_NO" NUMBER,
	"F_SYS_NO" NUMBER,
	"URL" VARCHAR2(1000 CHAR),
	"CALL_SCR" VARCHAR2(250 CHAR),
	"RQUST_BODY" CLOB,
	"RSPNS_BODY" CLOB,
	"HTTP_CODE" NUMBER,
	"LOG_DATE" DATE,
	"UP_CNT" NUMBER(10,0),
	"PR_REP" NUMBER(10,0),
	"AD_TRMNL_NM" VARCHAR2(50 CHAR),
	"UP_TRMNL_NM" VARCHAR2(50 CHAR)
   ) ;

