
  CREATE TABLE "YSPOS23"."IAS_POS_HELP_KEYS"
   (	"BLK_NAME" VARCHAR2(50 CHAR),
	"KEY_NO" VARCHAR2(30 CHAR),
	"HELP_A_DESC" VARCHAR2(150 CHAR),
	"HELP_E_DESC" VARCHAR2(150 CHAR),
	 CONSTRAINT "IASPOSHLPKEY_PK" PRIMARY KEY ("BLK_NAME", "KEY_NO")
  USING INDEX  ENABLE
   ) ;

