
  CREATE TABLE "YSPOS23"."IAS_POS_SERVER_DB_LINK"
   (	"SERVER_NO" NUMBER,
	"SERVER_NM" VARCHAR2(60 CHAR),
	"DB_LINK_NM" VARCHAR2(60 CHAR),
	"DB_SERVICE_NM" VARCHAR2(60 CHAR),
	"DB_LINK_DESC" VARCHAR2(60 CHAR),
	"DB_MAIN_SERVER" NUMBER(1,0) DEFAULT 0,
	"BRN_NO" NUMBER(6,0),
	"SRVR_TYP" NUMBER(5,0),
	 CONSTRAINT "IAS_POS_DB_LINK_PK" PRIMARY KEY ("SERVER_NO", "SERVER_NM")
  USING INDEX  ENABLE
   ) ;

