
  CREATE TABLE "YSPOS23"."IAS_POS_CUSTOMER_CARD_AMOUNT"
   (	"CARD_NO" VARCHAR2(60 CHAR),
	"CARD_AMT" NUMBER,
	"REM_CARD_AMT" NUMBER,
	"A_CY" VARCHAR2(7 CHAR),
	"C_CODE" VARCHAR2(15 CHAR),
	"PROCESSED" NUMBER(1,0) DEFAULT 0,
	"EXTERNAL_POST" NUMBER(5,0) DEFAULT 0,
	"AD_U_ID" NUMBER(5,0),
	"AD_DATE" DATE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"UP_CNT" NUMBER(10,0),
	"PR_REP" NUMBER(6,0),
	"AD_TRMNL_NM" VARCHAR2(50 CHAR),
	"UP_TRMNL_NM" VARCHAR2(50 CHAR),
	"CMP_NO" NUMBER(3,0) NOT NULL ENABLE,
	"BRN_NO" NUMBER(6,0) NOT NULL ENABLE,
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0),
	"CARD_DESC" VARCHAR2(250 CHAR),
	"REF_NO" VARCHAR2(30 CHAR),
	"CARD_SER" VARCHAR2(60 CHAR),
	"CARD_PSWRD" VARCHAR2(20 CHAR),
	"F_DATE" DATE,
	"T_DATE" DATE,
	"INACTIVE_FLG" NUMBER(1,0) DEFAULT 0,
	"FREE_FLG" NUMBER(1,0) DEFAULT 0,
	"STATE_TYP" NUMBER(1,0) DEFAULT 0,
	 CONSTRAINT "CST_CARD_AMT_PK" PRIMARY KEY ("CARD_NO")
  USING INDEX  ENABLE
   ) ;

