
  CREATE TABLE "YSPOS23"."IAS_POS_KEY_BRD_GRPS_DTL"
   (	"EXTRA_KEYPAD_NO" NUMBER,
	"KGRP_CODE" VARCHAR2(6 CHAR),
	"I_CODE" VARCHAR2(30 CHAR),
	"ITM_UNT" VARCHAR2(10 CHAR),
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0),
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0),
	 CONSTRAINT "IAS_PK_KGRPS_DTL" PRIMARY KEY ("EXTRA_KEYPAD_NO", "KGRP_CODE", "I_CODE")
  USING INDEX  ENABLE,
	 CONSTRAINT "IAS_FK_KGPS_DTL" FOREIGN KEY ("EXTRA_KEYPAD_NO", "KGRP_CODE")
	  REFERENCES "YSPOS23"."IAS_POS_KEY_BRD_GRPS_MST" ("EXTRA_KEYPAD_NO", "KGRP_CODE") ON DELETE CASCADE ENABLE
   ) ;

