
  CREATE TABLE "YSPOS23"."IAS_POS_PAY_RT_BILLS"
   (	"RT_BILL_NO" NUMBER(38,0),
	"RT_PAY_CUR" VARCHAR2(7 CHAR),
	"RT_PAY_AMT" NUMBER,
	"RT_PAY_RATE" NUMBER,
	"RT_BILL_PAY_AMT" NUMBER,
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0),
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0)
   ) ;

