
  CREATE GLOBAL TEMPORARY TABLE "YSPOS23"."IAS_POS_CUST_CARD_AMT_TMP"
   (	"CARD_NO" VARCHAR2(60 CHAR),
	 CONSTRAINT "CARD_CUST_AMT_TMP_PK" PRIMARY KEY ("CARD_NO") ENABLE
   ) ON COMMIT DELETE ROWS ;

