
  CREATE TABLE "YSPOS23"."IAS_POS_PAY_HST_RT_BILLS"
   (	"RT_BILL_NO" NUMBER(38,0),
	"RT_PAY_CUR" VARCHAR2(7 CHAR),
	"RT_PAY_AMT" NUMBER,
	"RT_PAY_RATE" NUMBER,
	"RT_BILL_PAY_AMT" NUMBER,
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0),
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0),
	 CONSTRAINT "FK_POSPAYHSTRTBILL_BILLNO" FOREIGN KEY ("RT_BILL_NO")
	  REFERENCES "YSPOS23"."IAS_POS_HST_RT_BILL_MST" ("RT_BILL_NO") ON DELETE CASCADE ENABLE
   ) ;

