
  CREATE TABLE "YSPOS23"."IAS_POS_HST_PAY_BILLS"
   (	"BILL_NO" NUMBER(38,0),
	"PAY_CUR" VARCHAR2(7 CHAR),
	"PAY_AMT" NUMBER,
	"PAY_RATE" NUMBER,
	"BILL_PAY_AMT" NUMBER,
	"BILL_DATE" DATE,
	"MACHINE_NO" NUMBER(5,0),
	"RT_BILL_NO" NUMBER(38,0),
	"CARD_NO" VARCHAR2(60 CHAR),
	"BILL_TYPE" NUMBER(2,0),
	"C_CODE" VARCHAR2(15 CHAR),
	"CARD_FREE_FLG" NUMBER(1,0) DEFAULT 0,
	"CARD_AMT_FREE" NUMBER,
	"AD_DATE" DATE,
	"AD_U_ID" NUMBER(5,0),
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0),
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0)
   ) ;

