
  CREATE TABLE "YSPOS23"."IAS_POS_PRIV_MACHINE"
   (	"U_ID" NUMBER(5,0),
	"MACHINE_NO" NUMBER(5,0),
	"USED" NUMBER(1,0) DEFAULT 0,
	"AD_U_ID" NUMBER(5,0),
	"AD_DATE" DATE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	 CONSTRAINT "IAS_POS_PRIV_MCH_PK" PRIMARY KEY ("U_ID", "MACHINE_NO")
  USING INDEX  ENABLE
   ) ;

