
  CREATE TABLE "YSPOS23"."IAS_POS_JRNL_DIFF_CSHR_MST"
   (	"DOC_NO" NUMBER NOT NULL ENABLE,
	"DOC_DATE" DATE NOT NULL ENABLE,
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0) NOT NULL ENABLE,
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0),
	"AD_U_ID" NUMBER(5,0),
	"AD_DATE" DATE,
	"PROCESS" NUMBER(1,0) DEFAULT 0,
	"DOC_SER" NUMBER NOT NULL ENABLE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"UP_CNT" NUMBER(10,0),
	"PR_REP" NUMBER(6,0),
	"GRP_CRD_CARD_RCRD_FLG" NUMBER(1,0) DEFAULT 1,
	 CONSTRAINT "IAS_POS_JRNL_DIFF_CSHR_PK" PRIMARY KEY ("DOC_SER")
  USING INDEX  ENABLE
   ) ;

