
  CREATE TABLE "YSPOS23"."MLOG$_IAS_POS_KEY_BRD_GRPS1"
   (	"M_ROW$$" VARCHAR2(255),
	"SNAPTIME$$" DATE,
	"DMLTYPE$$" VARCHAR2(1),
	"OLD_NEW$$" VARCHAR2(1),
	"CHANGE_VECTOR$$" RAW(255),
	"XID$$" NUMBER
   ) ;

