
  CREATE TABLE "YSPOS23"."MLOG$_POS_DFLT_STNG_DTL"
   (	"M_ROW$$" VARCHAR2(255),
	"SNAPTIME$$" DATE,
	"DMLTYPE$$" VARCHAR2(1),
	"OLD_NEW$$" VARCHAR2(1),
	"CHANGE_VECTOR$$" RAW(255),
	"XID$$" NUMBER
   ) ;

