
  CREATE TABLE "YSPOS23"."MV_IAS_POST_DTL"
   (	"A_CODE" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"A_CY" VARCHAR2(7 CHAR) NOT NULL ENABLE,
	"C_CODE" VARCHAR2(15 CHAR),
	"CC_CODE" VARCHAR2(30 CHAR),
	"ACTV_NO" VARCHAR2(15 CHAR),
	"PJ_NO" VARCHAR2(15 CHAR),
	"CMP_NO" NUMBER(3,0) NOT NULL ENABLE,
	"BRN_NO" NUMBER(6,0) NOT NULL ENABLE,
	"AC_CODE_DTL" VARCHAR2(30 CHAR),
	"AC_DTL_TYP" NUMBER(2,0),
	"C_V_CODE" VARCHAR2(15 CHAR),
	"V_C_CODE" VARCHAR2(15 CHAR),
	"DR_AMT" NUMBER,
	"CR_AMT" NUMBER,
	"DR_AMT_F" NUMBER,
	"CR_AMT_F" NUMBER,
	"AMT" NUMBER,
	"AMT_F" NUMBER,
	 CONSTRAINT "PK_MV_IAS_POST_DTL" PRIMARY KEY ("A_CODE", "A_CY", "C_CODE", "CC_CODE", "ACTV_NO", "PJ_NO", "CMP_NO", "BRN_NO", "AC_CODE_DTL", "AC_DTL_TYP", "C_V_CODE", "V_C_CODE")
  USING INDEX  ENABLE
   ) ;

