
  CREATE TABLE "YSPOS23"."MV_ITEM_AVL_QTY"
   (	"I_CODE" VARCHAR2(30 CHAR),
	"W_CODE" NUMBER(10,0),
	"EXPIRE_DATE" DATE,
	"BATCH_NO" VARCHAR2(30 CHAR),
	"AVL_QTY" NUMBER,
	 CONSTRAINT "PK_MV_ITEM_MOV" PRIMARY KEY ("I_CODE", "W_CODE", "EXPIRE_DATE", "BATCH_NO")
  USING INDEX  ENABLE
   ) ;

