
  CREATE TABLE "YSPOS23"."POS_INSTLMNT_CMPNY"
   (	"CMP_TYP" NUMBER,
	"MOBILE_NO" VARCHAR2(16 CHAR),
	"ORDERID" VARCHAR2(100 CHAR),
	"CHECKOUTID" VARCHAR2(100 CHAR),
	"BILL_AMT" NUMBER,
	"STATUS" VARCHAR2(100 CHAR),
	"UP_U_ID" NUMBER,
	"UP_DATE" DATE,
	"BILL_SER" NUMBER(38,0),
	"AD_DATE" DATE NOT NULL ENABLE,
	"AD_U_ID" NUMBER,
	"DOC_M_SQ" NUMBER,
	"CUR_CODE" VARCHAR2(7 CHAR),
	"BRN_NO" NUMBER(6,0),
	"REFUND_STATUS" VARCHAR2(100 CHAR),
	"QR_CODE" VARCHAR2(4000 CHAR)
   ) ;

