
  CREATE TABLE "YSPOS23"."POS_SYNC_MNGMNT"
   (	"TBL_NM" VARCHAR2(100 CHAR),
	"MV_NM" VARCHAR2(100 CHAR),
	"OWNR_TYP" NUMBER(1,0) NOT NULL ENABLE,
	"RFRSH_TYP" VARCHAR2(20 CHAR),
	"MV_WHR" VARCHAR2(4000 CHAR),
	"UPDT_FLG" NUMBER(1,0) DEFAULT 0,
	"DLT_FLG" NUMBER(1,0) DEFAULT 0,
	"STP_RFRSH_FLG" NUMBER(1,0) DEFAULT 0,
	"MV_FLG" NUMBER(1,0) DEFAULT 0,
	"SYNNYM_FLG" NUMBER(1,0) DEFAULT 0,
	"CRT_DATE" DATE,
	"UPD_DATE" DATE,
	"MV_CMMNT" VARCHAR2(1000 CHAR),
	"RFRSH_TIME_TYP" NUMBER(1,0),
	"RFRSH_TIME_VAL" NUMBER,
	"SYS_NO" NUMBER(5,0),
	"CTGRY_TYP" NUMBER(3,0),
	 CONSTRAINT "POS_SYNC_MNGMNT_PK" PRIMARY KEY ("TBL_NM")
  USING INDEX  ENABLE
   ) ;

