
  CREATE TABLE "YSPOS23"."POS_FNCL_ADVNC_CSHR"
   (	"SHFT_SRL" NUMBER,
	"CSHR_NO" NUMBER(5,0),
	"CSH_AMT" NUMBER,
	"CUR_CODE" VARCHAR2(7 CHAR),
	"CUR_RATE" NUMBER,
	"CUR_VALUE" NUMBER,
	"CUR_NMBR" NUMBER,
	"RCRD_NO" NUMBER,
	"AD_U_ID" NUMBER(5,0) NOT NULL ENABLE,
	"AD_DATE" DATE NOT NULL ENABLE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"UP_CNT" NUMBER(10,0),
	"PR_REP" NUMBER(6,0),
	"AD_TRMNL_NM" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"UP_TRMNL_NM" VARCHAR2(50 CHAR),
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0) NOT NULL ENABLE,
	"BRN_YEAR" NUMBER(4,0) NOT NULL ENABLE,
	"BRN_USR" NUMBER(3,0) NOT NULL ENABLE,
	"CASH_NO" NUMBER(12,0),
	"MACHINE_NO" NUMBER,
	 CONSTRAINT "POS_FNCL_ADVNC_CSHR_PK" PRIMARY KEY ("SHFT_SRL", "CSHR_NO", "CUR_CODE", "CUR_VALUE")
  USING INDEX  ENABLE
   ) ;

