
  CREATE TABLE "YSPOS23"."POS_BACKUP"
   (	"BK_NO" NUMBER(15,0),
	"BK_NAME" VARCHAR2(100 CHAR),
	"FILE_NAME" VARCHAR2(100 CHAR),
	"BK_DATE" DATE,
	"ENC_PASSWD" VARCHAR2(30 CHAR),
	"AD_U_ID" NUMBER(5,0),
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0),
	"BRN_YEAR" NUMBER(4,0),
	"BRN_USR" NUMBER(3,0),
	"AD_TRMNL_NM" VARCHAR2(50 CHAR),
	"UP_TRMNL_NM" VARCHAR2(50 CHAR)
   ) ;

