
  CREATE TABLE "YSPOS23"."POS_WRK_SHFT"
   (	"SHFT_CODE" VARCHAR2(10 CHAR),
	"SHFT_DSC" VARCHAR2(100 CHAR),
	"SHFT_DSC_F" VARCHAR2(100 CHAR),
	"ALLW_PRD_BFR" NUMBER,
	"ALLW_PRD_AFTR" NUMBER,
	"INTRFRNC_FLG" NUMBER,
	"F_DATE" DATE,
	"T_DATE" DATE,
	"INACTIVE" NUMBER(1,0) DEFAULT 0,
	"INACTIVE_RES" VARCHAR2(250 CHAR),
	"INACTIVE_DATE" DATE,
	"INACTIVE_U_ID" NUMBER(5,0),
	"CMP_NO" NUMBER(3,0),
	"BRN_NO" NUMBER(6,0) NOT NULL ENABLE,
	"AD_U_ID" NUMBER(5,0) NOT NULL ENABLE,
	"AD_DATE" DATE NOT NULL ENABLE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"UP_CNT" NUMBER(10,0),
	"PR_REP" NUMBER(6,0),
	"AD_TRMNL_NM" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"UP_TRMNL_NM" VARCHAR2(50 CHAR),
	"F_TIME_OLD" NUMBER,
	"T_TIME_OLD" NUMBER,
	"F_TIME" NUMBER,
	"T_TIME" NUMBER,
	"SHW_ALRT_BFR_END_SHFT" NUMBER DEFAULT 30,
	 CONSTRAINT "POS_WRK_SHFT_PK" PRIMARY KEY ("SHFT_CODE")
  USING INDEX  ENABLE
   ) ;

