
  CREATE TABLE "YSPOS23"."POS_DFLT_STNG_MST"
   (	"STNG_NO" NUMBER(5,0),
	"STNG_VAL" VARCHAR2(200 CHAR),
	"COMNT" VARCHAR2(100 CHAR),
	"AD_U_ID" NUMBER(5,0),
	"ORDR_NO" NUMBER(5,0),
	"INACTIVE" NUMBER(1,0),
	"INACTIVE_RES" VARCHAR2(250 CHAR),
	"INACTIVE_DATE" DATE,
	"INACTIVE_U_ID" NUMBER(5,0),
	"AD_DATE" DATE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"UP_CNT" NUMBER(10,0),
	"AD_TRMNL_NM" VARCHAR2(50 CHAR),
	"UP_TRMNL_NM" VARCHAR2(50 CHAR),
	 CONSTRAINT "POS_DFLT_STNG_MST_PK" PRIMARY KEY ("STNG_NO")
  USING INDEX  ENABLE
   ) ;

