
  CREATE TABLE "YSPOS23"."POS_SQL_QUEUE"
   (	"DOC_SRL" NUMBER,
	"SQL_STMNT" VARCHAR2(4000 CHAR),
	"EXEC_TIME" NUMBER,
	"FAILURE_DLT_FLG" NUMBER(1,0) DEFAULT 0,
	"ALLWD_RTRY_CNT" NUMBER(3,0) DEFAULT 3,
	"RTRY_CNT" NUMBER(3,0) DEFAULT 0,
	"AD_DATE" DATE
   ) ;

