
  CREATE TABLE "YSPOS23"."POS_DFLT_STNG_DTL"
   (	"STNG_NO" NUMBER(5,0),
	"MACHINE_NO" NUMBER(5,0),
	"STNG_MCHN_VAL" VARCHAR2(200 CHAR),
	"AD_U_ID" NUMBER(5,0),
	"INACTIVE" NUMBER(1,0),
	"INACTIVE_RES" VARCHAR2(250 CHAR),
	"INACTIVE_DATE" DATE,
	"INACTIVE_U_ID" NUMBER(5,0),
	"AD_DATE" DATE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"UP_CNT" NUMBER(10,0),
	"AD_TRMNL_NM" VARCHAR2(50 CHAR),
	"UP_TRMNL_NM" VARCHAR2(50 CHAR),
	 CONSTRAINT "POS_DFLT_STNG_DTL_PK" PRIMARY KEY ("STNG_NO", "MACHINE_NO")
  USING INDEX  ENABLE,
	 CONSTRAINT "POS_DFLT_STNG_DTL_FK" FOREIGN KEY ("STNG_NO")
	  REFERENCES "YSPOS23"."POS_DFLT_STNG_MST" ("STNG_NO") ENABLE
   ) ;

