
  CREATE TABLE "YSPOS23"."POS_BILL_TRC"
   (	"BILL_NO" NUMBER,
	"ITM_CODE" VARCHAR2(200 CHAR),
	"I_NAME" VARCHAR2(200 CHAR),
	"DOC_D_SEQ" NUMBER,
	"RCRD_NO" NUMBER,
	"I_QTY" NUMBER,
	"I_PRICE" NUMBER,
	"CODE_TYPE" VARCHAR2(60 CHAR),
	"TYP" NUMBER,
	"MACHINE_NO" NUMBER
   ) ;

