
  CREATE TABLE "YSPOS23"."POS_BILL_FREE_QTY_PRM_TMP"
   (	"BILL_NO" NUMBER(38,0),
	"BILL_SEQ" NUMBER,
	"I_CODE" VARCHAR2(30 CHAR),
	"QT_PRM_I_CODE" VARCHAR2(30 CHAR),
	"ITM_UNT" VARCHAR2(10 CHAR),
	"QT_PRM_FREE_QTY" NUMBER,
	"QT_PRM_NO" NUMBER(15,0),
	"QT_PRM_SER" NUMBER(38,0),
	"QT_PRM_RCRD_NO" NUMBER(10,0),
	"QT_PRM_METHOD" NUMBER(3,0),
	"QT_PRM_ITM_UNT" VARCHAR2(10 CHAR)
   ) ;

