
  CREATE TABLE "YSPOS23"."POS_EXTRNL_DOC_SYNC"
   (	"PLATFORM_NO" NUMBER(5,0),
	"PLATFORM_L_DSC" VARCHAR2(100 CHAR),
	"PLATFORM_F_DSC" VARCHAR2(100 CHAR),
	"DOC_TYPE" NUMBER NOT NULL ENABLE,
	"DOC_NO" NUMBER NOT NULL ENABLE,
	"DOC_SER" NUMBER NOT NULL ENABLE,
	"SYNC_FLG" NUMBER(1,0) DEFAULT (0),
	"SYNC_RSLT" VARCHAR2(4000 CHAR),
	"SYNC_DATE" DATE,
	"DOC_SER_EXTRNL" VARCHAR2(128 CHAR),
	"SYNC_RQST" VARCHAR2(4000 CHAR)
   ) ;

