
  CREATE TABLE "YSPOS23"."POS_DFLT_GRP_DTL"
   (	"STNG_NO" NUMBER(5,0),
	"STNG_VAL" VARCHAR2(200 CHAR),
	"GRP_NO" VARCHAR2(10 CHAR),
	"GRP_ITM_COLOR" VARCHAR2(30 CHAR),
	"GRP_FONT_COLOR" VARCHAR2(30 CHAR),
	"GRP_COLOR" VARCHAR2(30 CHAR),
	"GRP_ITM_FONT_COLOR" VARCHAR2(30 CHAR),
	"INACTIVE" NUMBER(1,0) DEFAULT 0,
	"INACTIVE_RES" VARCHAR2(250 CHAR),
	"INACTIVE_DATE" DATE,
	"INACTIVE_U_ID" NUMBER(5,0),
	"AD_U_ID" NUMBER(5,0),
	"AD_DATE" DATE,
	"UP_U_ID" NUMBER(5,0),
	"UP_DATE" DATE,
	"UP_CNT" NUMBER(10,0),
	"PR_REP" NUMBER(6,0),
	"AD_TRMNL_NM" VARCHAR2(50 CHAR),
	"UP_TRMNL_NM" VARCHAR2(50 CHAR),
	 CONSTRAINT "POS_DFLT_GRP_DTL_PK" PRIMARY KEY ("STNG_NO", "STNG_VAL", "GRP_NO")
  USING INDEX  ENABLE
   ) ;

