
  CREATE TABLE "YSPOS23"."POS_S_FLD_PRV_FXD_USR"
   (	"U_ID" NUMBER(5,0),
	"FLD_NM" VARCHAR2(30 CHAR),
	"FLD_VAL" VARCHAR2(500 CHAR),
	"AD_U_ID" NUMBER(10,0) NOT NULL ENABLE,
	"AD_DATE" DATE NOT NULL ENABLE,
	"AD_TRMNL_NM" VARCHAR2(50 CHAR),
	"UP_U_ID" NUMBER(10,0),
	"UP_DATE" DATE,
	"UP_CNT" NUMBER(30,0) DEFAULT 0,
	"UP_TRMNL_NM" VARCHAR2(50 CHAR),
	 CONSTRAINT "PK_POS_S_FLD_PRV_FXD_USR" PRIMARY KEY ("U_ID", "FLD_NM")
  USING INDEX  ENABLE
   ) ;

