
  CREATE TABLE "YSPOS23"."POS_S_FLD_PRV_FXD"
   (	"FLD_NM" VARCHAR2(30 CHAR),
	"FLD_LBL_NO" NUMBER NOT NULL ENABLE,
	"FLD_LBL_NO2" NUMBER,
	"FLD_TYP" NUMBER(1,0) DEFAULT 0,
	"FLD_LNGTH" NUMBER,
	"FLD_ORDR" NUMBER(5,0),
	"FLD_ST_FLG" NUMBER(1,0) DEFAULT 1,
	"FLD_CHKBOX_FLG" NUMBER(1,0) DEFAULT 0,
	"FLD_VSBL_SLCT" VARCHAR2(2000 CHAR),
	"FLD_UPDTD_SLCT" VARCHAR2(2000 CHAR),
	"FLD_DFLT_VAL" VARCHAR2(500 CHAR),
	"FLD_SYS" VARCHAR2(15 CHAR),
	"FLD_LOV_NM" VARCHAR2(30 CHAR),
	"FLD_LOV_WHR" VARCHAR2(500 CHAR),
	"FLD_LOV_RTRN_CLMN_NM" VARCHAR2(30 CHAR),
	"FLD_LOV_WHR_CLMN_NM" VARCHAR2(30 CHAR),
	"AD_TRMNL_NM" VARCHAR2(50 CHAR),
	"UP_TRMNL_NM" VARCHAR2(50 CHAR),
	"FLD_REQUIRED" NUMBER(1,0) DEFAULT 0,
	"FLD_LWST_ALLW_VAL" NUMBER,
	"FLD_HGHST_ALLW_VAL" NUMBER,
	 CONSTRAINT "PK_POS_S_FLD_PRV_FXD" PRIMARY KEY ("FLD_NM")
  USING INDEX  ENABLE
   ) ;

