import type { SettingGroup, SettingType } from './ports/settings-repository.port';

/**
 * SETTINGS_CATALOG — the full classification of ALL 179 IAS_PARA_POS columns
 * (source: docs/SETTINGS_CLASSIFIED.txt, derived from YSPOS23.IAS_PARA_POS).
 * Each entry: Oracle column name (= canonical overlay key for raw settings),
 * Oracle data type, functional group, and an Arabic description for the most
 * commonly-used settings. Order matches the physical column order.
 */
export interface SettingCatalogEntry {
  column: string;
  type: SettingType;
  group: SettingGroup;
  /** وصف عربي (متوفر لأهم الإعدادات الشائعة). */
  description?: string;
}

export const SETTINGS_CATALOG: readonly SettingCatalogEntry[] = [
  { column: 'SETTING_NAME', type: 'VARCHAR2', group: 'behavior', description: 'اسم المتجر / ملف الإعدادات' },
  { column: 'SETTING_DATE', type: 'DATE', group: 'behavior' },
  { column: 'LENGTHED_PERFIX', type: 'VARCHAR2', group: 'numbering', description: 'بادئة باركود الأصناف المطوّلة' },
  { column: 'LENGTHED_LENGTH', type: 'NUMBER', group: 'numbering', description: 'طول باركود الأصناف المطوّلة' },
  { column: 'LENGTHED_ITEM_LENGTH', type: 'NUMBER', group: 'numbering', description: 'طول كود الصنف داخل الباركود المطوّل' },
  { column: 'LENGTHED_BASIC', type: 'NUMBER', group: 'numbering', description: 'أساس القيمة في الباركود المطوّل' },
  { column: 'LENGTHED', type: 'NUMBER', group: 'numbering', description: 'تفعيل باركود الأصناف المطوّلة' },
  { column: 'WEIGHTED_PERFIX', type: 'VARCHAR2', group: 'numbering', description: 'بادئة باركود الأصناف الموزونة' },
  { column: 'WEIGHTED_LENGTH', type: 'NUMBER', group: 'numbering', description: 'طول باركود الأصناف الموزونة' },
  { column: 'WEIGHTED_ITEM_LENGTH', type: 'NUMBER', group: 'numbering', description: 'طول كود الصنف داخل باركود الوزن' },
  { column: 'WEIGHTED_BASIC', type: 'NUMBER', group: 'behavior' },
  { column: 'WEIGHTED', type: 'NUMBER', group: 'behavior', description: 'تفعيل باركود الأصناف الموزونة' },
  { column: 'MACHINE_DIGIT', type: 'NUMBER', group: 'numbering', description: 'عدد خانات رقم الجهاز في تسلسل الفاتورة' },
  { column: 'USER_DIGIT', type: 'NUMBER', group: 'numbering', description: 'عدد خانات رقم المستخدم في تسلسل الفاتورة' },
  { column: 'SERIAL_DIGIT', type: 'NUMBER', group: 'numbering', description: 'عدد خانات الرقم التسلسلي للفاتورة' },
  { column: 'MAXHUNGS', type: 'NUMBER', group: 'behavior', description: 'الحد الأقصى لعدد الفواتير المعلّقة' },
  { column: 'OPEN_DRAWER', type: 'NUMBER', group: 'behavior', description: 'فتح درج النقود تلقائياً' },
  { column: 'PRINT_BILL', type: 'NUMBER', group: 'printing', description: 'طباعة الفاتورة بعد الحفظ' },
  { column: 'POS_BILL_SERIAL', type: 'NUMBER', group: 'numbering', description: 'تسلسل فواتير نقطة البيع' },
  { column: 'PRICE_LEVEL', type: 'VARCHAR2', group: 'behavior', description: 'مستوى السعر الافتراضي' },
  { column: 'USE_HUNG_BILLS', type: 'NUMBER', group: 'printing', description: 'تفعيل الفواتير المعلّقة' },
  { column: 'POS_PRICING_TYPE', type: 'NUMBER', group: 'behavior', description: 'نوع التسعير في نقطة البيع' },
  { column: 'CURR_DFLT', type: 'VARCHAR2', group: 'currency', description: 'العملة الافتراضية' },
  { column: 'SHOW_PAYED_AMT', type: 'NUMBER', group: 'behavior', description: 'عرض المبلغ المدفوع' },
  { column: 'POST_ITM_FRST_EXPDATE', type: 'NUMBER', group: 'behavior' },
  { column: 'ALLOW_CHANGE_BILL_CURR', type: 'NUMBER', group: 'printing', description: 'السماح بتغيير عملة الفاتورة' },
  { column: 'USE_CHECK_SUM', type: 'NUMBER', group: 'behavior', description: 'استخدام رقم التحقق (Check digit) في الباركود' },
  { column: 'AUDIT_DEL_ITM', type: 'NUMBER', group: 'behavior', description: 'تدقيق حذف الأصناف' },
  { column: 'DAY_NOTIFY_HUNG_BILL', type: 'NUMBER', group: 'printing', description: 'عدد أيام التنبيه على الفواتير المعلّقة' },
  { column: 'USE_DEL_SHIFTF6', type: 'NUMBER', group: 'behavior' },
  { column: 'RETURN_CHANGE_TYPE', type: 'NUMBER', group: 'behavior' },
  { column: 'RETURN_PERIOD', type: 'NUMBER', group: 'behavior', description: 'فترة السماح بالإرجاع (أيام)' },
  { column: 'CHANGE_PERIOD', type: 'NUMBER', group: 'behavior', description: 'فترة السماح بالاستبدال (أيام)' },
  { column: 'REMOVE_WEIGHT_DIGIT', type: 'NUMBER', group: 'numbering', description: 'حذف خانة الوزن من الباركود' },
  { column: 'USE_PAY_CASH_RT_BILLS', type: 'NUMBER', group: 'printing' },
  { column: 'OPEN_BILL_MORE_ONE', type: 'NUMBER', group: 'printing' },
  { column: 'OPEN_SYS_MORE_ONE', type: 'NUMBER', group: 'behavior' },
  { column: 'USE_PAID', type: 'NUMBER', group: 'behavior' },
  { column: 'USE_F12_KEY', type: 'NUMBER', group: 'behavior' },
  { column: 'ALLOW_PRINT_HUNG_BILL', type: 'NUMBER', group: 'printing', description: 'السماح بطباعة الفاتورة المعلّقة' },
  { column: 'USE_SEC_KEY_IN_CR_SALE', type: 'NUMBER', group: 'behavior' },
  { column: 'P_ENTER_MAN_ICODE', type: 'NUMBER', group: 'behavior' },
  { column: 'P_ENTER_EMP_MNDTRY', type: 'NUMBER', group: 'behavior' },
  { column: 'NOT_SHOW_NET_AMT_IN_DEP_CASH', type: 'NUMBER', group: 'behavior' },
  { column: 'CASH_NO', type: 'NUMBER', group: 'behavior' },
  { column: 'RETURN_A_CODE', type: 'VARCHAR2', group: 'behavior' },
  { column: 'COUPON_A_CODE', type: 'VARCHAR2', group: 'coupons', description: 'كود حساب الكوبونات' },
  { column: 'USE_PREV_PAID_CARD', type: 'NUMBER', group: 'cards', description: 'تفعيل البطاقات مسبقة الدفع' },
  { column: 'USE_CARD_MORE_ONE', type: 'NUMBER', group: 'cards', description: 'السماح باستخدام البطاقة أكثر من مرة' },
  { column: 'SHOW_C_NAME', type: 'NUMBER', group: 'behavior', description: 'عرض اسم العميل' },
  { column: 'USE_CREDIT_LIMIT_IN_POS', type: 'NUMBER', group: 'behavior' },
  { column: 'AUDIT_HUNG_BILL', type: 'NUMBER', group: 'printing' },
  { column: 'LIMIT_REM_CASH_AMT_AFTER_SALE', type: 'NUMBER', group: 'behavior' },
  { column: 'USE_F9_KEY_TO_VIEW_ITM', type: 'NUMBER', group: 'behavior' },
  { column: 'POS_USE_FREE_QTY', type: 'NUMBER', group: 'behavior' },
  { column: 'PRINT_BILL_B4SAV', type: 'NUMBER', group: 'printing', description: 'طباعة الفاتورة قبل الحفظ' },
  { column: 'SHOW_QTY_IN_DEL_SCRN', type: 'NUMBER', group: 'behavior' },
  { column: 'GNRT_JRNL_DIFF_CASHR', type: 'NUMBER', group: 'behavior' },
  { column: 'ROUND_AMT_FRCTION', type: 'NUMBER', group: 'behavior', description: 'كسر تقريب مبلغ الفاتورة' },
  { column: 'USE_BARCODE_ONLY', type: 'NUMBER', group: 'behavior', description: 'إدخال الأصناف بالباركود فقط' },
  { column: 'NOT_ALLOW_SAL_NOT_PAY', type: 'NUMBER', group: 'behavior' },
  { column: 'PRD_BACK_HOUR', type: 'NUMBER', group: 'behavior' },
  { column: 'HNG_BILLS_AUDIT', type: 'NUMBER', group: 'printing' },
  { column: 'SHOW_TOOLBAR', type: 'NUMBER', group: 'behavior' },
  { column: 'COLLCT_RPT_ITM_PRNT', type: 'NUMBER', group: 'behavior' },
  { column: 'SHOW_AVLQTY_IN_BILL', type: 'NUMBER', group: 'printing', description: 'عرض الكمية المتاحة في شاشة الفاتورة' },
  { column: 'ALLOW_SLCT_ITM_UNT', type: 'NUMBER', group: 'behavior' },
  { column: 'FTR_BILL', type: 'VARCHAR2', group: 'printing', description: 'نص تذييل الفاتورة' },
  { column: 'SHOW_ITM_IMG_IN_BILL', type: 'NUMBER', group: 'printing', description: 'عرض صورة الصنف في شاشة الفاتورة' },
  { column: 'USE_POS_POINT_SYS', type: 'NUMBER', group: 'points', description: 'تفعيل نظام نقاط الولاء' },
  { column: 'POINT_CALC_TYP', type: 'NUMBER', group: 'points', description: 'طريقة احتساب النقاط' },
  { column: 'PRNT_CNT_POINT', type: 'NUMBER', group: 'points', description: 'طباعة رصيد النقاط في الفاتورة' },
  { column: 'POINT_AMT_SAME_RPLC_AMT', type: 'NUMBER', group: 'points', description: 'مساواة مبلغ النقاط بمبلغ الاستبدال' },
  { column: 'POINT_APRVD_BY_DAY', type: 'NUMBER', group: 'points', description: 'اعتماد النقاط حسب اليوم' },
  { column: 'POINT_AGE_EXPIRED_TYP', type: 'NUMBER', group: 'points', description: 'نوع انتهاء صلاحية النقاط' },
  { column: 'POINT_AGE_EXPIRED_PRD', type: 'NUMBER', group: 'points', description: 'مدة انتهاء صلاحية النقاط' },
  { column: 'CUST_NOTE_JOIN_POINT', type: 'VARCHAR2', group: 'points' },
  { column: 'CUST_NOTE_NOT_JOIN_POINT', type: 'VARCHAR2', group: 'points' },
  { column: 'AUTO_FILL_CARD_IN_BILL', type: 'NUMBER', group: 'printing' },
  { column: 'POST_OTHR_CHR_ITM', type: 'NUMBER', group: 'behavior' },
  { column: 'UP_CNT', type: 'NUMBER', group: 'behavior' },
  { column: 'PR_REP', type: 'NUMBER', group: 'behavior' },
  { column: 'AD_TRMNL_NM', type: 'VARCHAR2', group: 'behavior' },
  { column: 'UP_TRMNL_NM', type: 'VARCHAR2', group: 'behavior' },
  { column: 'UP_U_ID', type: 'NUMBER', group: 'behavior' },
  { column: 'UP_DATE', type: 'DATE', group: 'behavior' },
  { column: 'USE_DISC_CARD', type: 'NUMBER', group: 'cards', description: 'تفعيل بطاقات الخصم' },
  { column: 'USE_SALE_ORDER', type: 'NUMBER', group: 'behavior', description: 'تفعيل أوامر البيع' },
  { column: 'INSTL_FREE_QTY_PRM_TYP', type: 'NUMBER', group: 'coupons' },
  { column: 'ROUND_DISC_PER_ITM_TYP', type: 'NUMBER', group: 'cards' },
  { column: 'CHCK_AVL_QTY', type: 'NUMBER', group: 'behavior' },
  { column: 'RTRN_FREE_QTY_TYP', type: 'NUMBER', group: 'behavior' },
  { column: 'SEND_MSG_TYP', type: 'NUMBER', group: 'messages' },
  { column: 'SEND_MSG_CST_TYP', type: 'NUMBER', group: 'messages' },
  { column: 'MSG_TXT_CST_BILL', type: 'VARCHAR2', group: 'printing', description: 'نص رسالة العميل على فاتورة البيع النقدي' },
  { column: 'MSG_TXT_CST_BILL_CRDT', type: 'VARCHAR2', group: 'printing', description: 'نص رسالة العميل على فاتورة البيع الآجل' },
  { column: 'MSG_TXT_CST_RTBILL', type: 'VARCHAR2', group: 'printing', description: 'نص رسالة العميل على فاتورة المرتجع' },
  { column: 'MSG_TXT_CST_RTBILL_CRDT', type: 'VARCHAR2', group: 'printing' },
  { column: 'MSG_TXT_CST_POINT', type: 'VARCHAR2', group: 'points', description: 'نص رسالة نقاط العميل' },
  { column: 'NOT_CLC_PRM_ITM_IN_POINT', type: 'NUMBER', group: 'points' },
  { column: 'IP', type: 'VARCHAR2', group: 'behavior' },
  { column: 'BALANCE_TYPE', type: 'NUMBER', group: 'behavior' },
  { column: 'PRD_BACK_INCRS_TYP', type: 'NUMBER', group: 'behavior' },
  { column: 'RTRN_COUPON_BILL', type: 'NUMBER', group: 'printing' },
  { column: 'PRD_BACK_INCRS_F_DATE', type: 'DATE', group: 'behavior' },
  { column: 'PRD_BACK_INCRS_T_DATE', type: 'DATE', group: 'behavior' },
  { column: 'GRP_QTY_4ITM_HAV_PRM', type: 'NUMBER', group: 'coupons' },
  { column: 'WEIGHTED_INCLD_ITM_UNT', type: 'NUMBER', group: 'behavior' },
  { column: 'MAX_LMT_QTY_4ITM', type: 'NUMBER', group: 'behavior' },
  { column: 'LENGTH_CSTMR_CODE', type: 'NUMBER', group: 'numbering', description: 'طول كود العميل' },
  { column: 'LENGTH_CSTMR_MOBL_NO', type: 'NUMBER', group: 'numbering', description: 'طول رقم جوال العميل' },
  { column: 'MSG_TXT_CST_WELCOME', type: 'VARCHAR2', group: 'messages', description: 'نص رسالة الترحيب بالعميل' },
  { column: 'USE_MDCN_DESC', type: 'NUMBER', group: 'behavior' },
  { column: 'CNCT_DISC_CARD_CSTMR_TYP', type: 'NUMBER', group: 'cards' },
  { column: 'SHW_PRICE_BFR_PRM', type: 'NUMBER', group: 'coupons' },
  { column: 'USE_EMP_NO', type: 'NUMBER', group: 'behavior' },
  { column: 'USE_REP_CODE', type: 'NUMBER', group: 'behavior' },
  { column: 'USE_DISC_CRD_BY_PUR_VAL', type: 'NUMBER', group: 'cards' },
  { column: 'CLC_CRD_DISC_TYPE', type: 'NUMBER', group: 'cards' },
  { column: 'USE_APRVD_IN_RTBILL', type: 'NUMBER', group: 'printing' },
  { column: 'SHW_ITM_PRICE_TOTL_BY_NET', type: 'NUMBER', group: 'behavior' },
  { column: 'CRDT_CRD_CST_MNDTRY', type: 'NUMBER', group: 'cards' },
  { column: 'CSTMR_CODE_MNDTRY', type: 'NUMBER', group: 'customers', description: 'كود العميل إلزامي' },
  { column: 'CRDT_CRD_DSC_MNDTRY', type: 'NUMBER', group: 'cards' },
  { column: 'CPN_EXPIRE_DATE_MNDTRY', type: 'NUMBER', group: 'coupons', description: 'تاريخ انتهاء الكوبون إلزامي' },
  { column: 'CHK_PRV_RT_QTY_OTHR_SRVR', type: 'NUMBER', group: 'behavior' },
  { column: 'DPST_TYP', type: 'NUMBER', group: 'currency' },
  { column: 'SHW_SCRN_CSTMR_BFR_PYD', type: 'NUMBER', group: 'customers' },
  { column: 'RTRN_ALL_ITM_BILL_HAV_FPRM', type: 'NUMBER', group: 'printing' },
  { column: 'SND_VRFCT_MSG_BFR_RPLC_POINT', type: 'NUMBER', group: 'points', description: 'إرسال رسالة تحقق قبل استبدال النقاط' },
  { column: 'DO_MOR_TSK_WHN_CHNG_USR', type: 'NUMBER', group: 'behavior' },
  { column: 'CSTMR_CODE_ADD_TYP', type: 'NUMBER', group: 'customers' },
  { column: 'MOBILE_NO_MNDTRY', type: 'NUMBER', group: 'customers', description: 'رقم جوال العميل إلزامي' },
  { column: 'ROUND_AMT_TYP', type: 'NUMBER', group: 'behavior', description: 'طريقة تقريب مبلغ الفاتورة' },
  { column: 'CHRG_NO', type: 'NUMBER', group: 'behavior' },
  { column: 'OUT_BILL_POST_TYP', type: 'NUMBER', group: 'printing' },
  { column: 'NUM_OF_DAYS_SHW_BILLS', type: 'NUMBER', group: 'printing', description: 'عدد الأيام لعرض الفواتير السابقة' },
  { column: 'RT_THEM_NO', type: 'NUMBER', group: 'behavior' },
  { column: 'ADD_CSTMR_CSH_FRM_BILL', type: 'NUMBER', group: 'printing' },
  { column: 'USE_ADVNC_PYMNT_TYP', type: 'NUMBER', group: 'behavior' },
  { column: 'SND_VRFCT_MSG_BFR_ADD_CSTMR', type: 'NUMBER', group: 'customers' },
  { column: 'SND_VRFCT_MSG_BFR_RTRN_POINT', type: 'NUMBER', group: 'points' },
  { column: 'SND_VRFCT_MSG_FOR_CRDT_BILL', type: 'NUMBER', group: 'printing' },
  { column: 'USE_RCPTS_FLG', type: 'NUMBER', group: 'behavior', description: 'تفعيل سندات القبض' },
  { column: 'USE_EXPNS_FLG', type: 'NUMBER', group: 'behavior', description: 'تفعيل سندات الصرف' },
  { column: 'USE_WRK_SHFT', type: 'NUMBER', group: 'behavior', description: 'تفعيل ورديات العمل' },
  { column: 'WRK_SHFT_TYP', type: 'NUMBER', group: 'behavior', description: 'نوع وردية العمل' },
  { column: 'OPN_SHFT_TYP', type: 'NUMBER', group: 'behavior' },
  { column: 'SHW_ALL_ITM_UNT_IN_PRC_READER', type: 'NUMBER', group: 'behavior' },
  { column: 'RTRN_IN_OTHR_SAL_BRN', type: 'NUMBER', group: 'behavior' },
  { column: 'RTRN_RPLC_IN_OTHR_RTSAL_BRN', type: 'NUMBER', group: 'behavior' },
  { column: 'RTRN_PYD_CSH_IN_OTHR_RTSAL_BRN', type: 'NUMBER', group: 'behavior' },
  { column: 'CLLCT_ITM_QTY_IN_BILL', type: 'NUMBER', group: 'printing' },
  { column: 'CLC_QT_PRM_IN_PYMNT', type: 'NUMBER', group: 'coupons' },
  { column: 'REPCODE_MANDTRY', type: 'NUMBER', group: 'behavior' },
  { column: 'SMBL_SPRT_WGHT_ITM', type: 'VARCHAR2', group: 'behavior' },
  { column: 'SHW_TOT_QTY_BY_ITM_IN_BILL', type: 'NUMBER', group: 'printing' },
  { column: 'PST_FRST_EXPDATE_BY_MN_UNT', type: 'NUMBER', group: 'behavior' },
  { column: 'MAX_LMT_PRC_4ITM', type: 'NUMBER', group: 'behavior' },
  { column: 'PST_CRDT_CRD_TO_AR_TYP', type: 'NUMBER', group: 'cards' },
  { column: 'CHK_PST_AMT_VAT_TO_AR', type: 'NUMBER', group: 'tax', description: 'فحص ترحيل مبلغ الضريبة (VAT) إلى الذمم' },
  { column: 'ALLW_UPDATE_PRICE', type: 'NUMBER', group: 'behavior' },
  { column: 'USE_BILL_TRC', type: 'NUMBER', group: 'printing', description: 'تفعيل تتبّع الفاتورة' },
  { column: 'ENTR_QR_FOR_ITM_USD_QR', type: 'NUMBER', group: 'behavior' },
  { column: 'SND_VRFCT_MSG_FOR_RTRN_BILL', type: 'NUMBER', group: 'printing' },
  { column: 'PARA_NO', type: 'NUMBER', group: 'behavior' },
  { column: 'USE_WHTRNS', type: 'NUMBER', group: 'behavior' },
  { column: 'USE_AUTO_APPRVD_RQST', type: 'NUMBER', group: 'behavior' },
  { column: 'ALLW_CHNG_EXPDAT_BTCH_QR', type: 'NUMBER', group: 'behavior' },
  { column: 'SHW_STK_CST_BY_PRV', type: 'NUMBER', group: 'behavior' },
  { column: 'USE_LNK_CPN_API', type: 'NUMBER', group: 'coupons' },
  { column: 'CPN_MAX_CNT', type: 'NUMBER', group: 'coupons', description: 'الحد الأقصى لعدد الكوبونات' },
  { column: 'CPN_VAL', type: 'NUMBER', group: 'coupons', description: 'قيمة الكوبون' },
  { column: 'AR_INV_EFCT_MTHD_PST_TYP', type: 'NUMBER', group: 'behavior' },
  { column: 'USE_APRVD_IN_DPST', type: 'NUMBER', group: 'currency' },
  { column: 'ROUND_AMT_TYP_RTRN', type: 'NUMBER', group: 'behavior' },
  { column: 'ROUND_AMT_FRCTION_RTRN', type: 'NUMBER', group: 'behavior' },
  { column: 'HTL_SYS_LNK_FLG', type: 'NUMBER', group: 'behavior' },
  { column: 'HTL_SYS_WEB_SRVC_IP', type: 'VARCHAR2', group: 'behavior' },
];

/** Fast lookup: column name -> catalog entry. */
export const SETTINGS_CATALOG_BY_COLUMN: ReadonlyMap<string, SettingCatalogEntry> =
  new Map(SETTINGS_CATALOG.map((e) => [e.column, e]));
