-- FUNCTION: POS_CRT_MV_FNC (status: VALID)
CREATE OR REPLACE
FUNCTION POS_CRT_MV_FNC (P_SQL VARCHAR2)
    RETURN NUMBER
IS
BEGIN
    EXECUTE IMMEDIATE P_SQL;

    RETURN NULL;
EXCEPTION
    WHEN OTHERS
    THEN
	IF SQLCODE = -00942 THEN
	    RETURN 942;
	ELSIF SQLCODE = -23413 THEN
	    RETURN 23413;
	ELSIF SQLCODE = -01031 THEN
	    RETURN 1031;
	ELSE
	    RETURN NULL;
	END IF;
END POS_CRT_MV_FNC;
/
