-- =============================================
-- PACKAGE SPEC: POS_RCPTS_EXPNS_API_PKG  (status: INVALID)
-- =============================================
CREATE OR REPLACE
PACKAGE POS_RCPTS_EXPNS_API_PKG
IS
    G_DOC_NO			 POS_GNR_RCPTS.DOC_NO%TYPE;
    G_DOC_SRL			 POS_GNR_RCPTS.DOC_SRL%TYPE;
    G_BRN_NO			 POS_GNR_RCPTS.BRN_NO%TYPE;
    G_USR_NO			 POS_GNR_RCPTS.AD_U_ID%TYPE;
    G_CMP_NO			 POS_GNR_RCPTS.CMP_NO%TYPE;
    G_BRN_YEAR			 POS_GNR_RCPTS.BRN_YEAR%TYPE;
    G_BRN_USR			 POS_GNR_RCPTS.BRN_USR%TYPE;
    G_TRMNL_NO			 POS_GNR_RCPTS.MACHINE_NO%TYPE;
    G_AD_DATE			 POS_GNR_RCPTS.AD_DATE%TYPE;

    G_LNG_NO			 NUMBER := 1;
    G_LBL_NO			 NUMBER;
    G_MSG_NO			 NUMBER;
    G_MSG_TXT			 VARCHAR2(1000) := NULL;
    G_SRVR_NO			 NUMBER;
    G_CASH_NO			 NUMBER;

    G_USE_WRK_SHFT		 NUMBER;
    V_ERR_MSG			 VARCHAR2 (1000);
    V_WHR			 VARCHAR2(1000);

    FUNCTION LOAD_PRMTRS RETURN VARCHAR2;
    FUNCTION GET_PYMNT_TYPE(P_LANG_NO IN IAS_LABELS.LANG_NO%TYPE,
			    P_USR_NO  IN USER_R.U_ID%TYPE DEFAULT NULL) RETURN CLOB;

    FUNCTION GET_CRRNCS(P_LANG_NO IN IAS_LABELS.LANG_NO%TYPE) RETURN CLOB;

    FUNCTION GET_CR_CARD_TYPES(P_LANG_NO IN IAS_LABELS.LANG_NO%TYPE) RETURN CLOB;

    FUNCTION GET_BNK(P_LANG_NO	IN IAS_LABELS.LANG_NO%TYPE,
		     P_USR_NO	IN USER_R.U_ID%TYPE) RETURN CLOB;

    FUNCTION GET_CRDT_CRDS(P_LANG_NO  IN IAS_LABELS.LANG_NO%TYPE,
			   P_TRMNL_NO IN IAS_POS_BILL_MST.MACHINE_NO%TYPE) RETURN CLOB;

    FUNCTION GET_CSTMR_ORDRS(P_LANG_NO	IN IAS_LABELS.LANG_NO%TYPE,
			     P_USR_NO	 IN USER_R.U_ID%TYPE,
			     P_ORDER_SER IN SALES_ORDER.ORDER_SER%TYPE	DEFAULT NULL ) RETURN CLOB;
    FUNCTION GET_CSTMR_ORDRS_LST(P_LANG_NO   IN IAS_LABELS.LANG_NO%TYPE,
				 P_USR_NO    IN USER_R.U_ID%TYPE,
				 P_ORDER_SER IN SALES_ORDER.ORDER_SER%TYPE  DEFAULT NULL,
				 P_WHR	     IN VARCHAR2 DEFAULT NULL ) RETURN CLOB;
    FUNCTION INSRT_RCPTS(P_XML_INPT IN CLOB,P_ONLINE_FLG NUMBER) RETURN VARCHAR2;

    FUNCTION INSRT_EXPNS(P_XML_INPT IN CLOB,P_ONLINE_FLG NUMBER) RETURN VARCHAR2;

    FUNCTION GET_CSTMR_DATA(P_DOC_SRL_REF IN SALES_ORDER.ORDER_SER%TYPE) RETURN CLOB;

    FUNCTION GET_ACCNT_LST (P_LANG_NO	 IN IAS_LABELS.LANG_NO%TYPE,
			    P_USR_NO	 IN USER_R.U_ID%TYPE,
			    P_AC_DTL_TYP IN NUMBER DEFAULT NULL,
			    P_WHR	 IN VARCHAR2 DEFAULT NULL)   --##0 GNRL 3-CUSTOMER  4-Dept 5-Credit 7-Emp
	RETURN CLOB;

    FUNCTION GET_ACCNT_DTL_LST(P_LANG_NO    IN IAS_LABELS.LANG_NO%TYPE,
			       P_USR_NO     IN USER_R.U_ID%TYPE,
			       P_AC_DTL_TYP IN POS_GNR_RCPTS.AC_DTL_TYP%TYPE,
			       P_AC_CODE    IN POS_GNR_RCPTS.A_CODE%TYPE DEFAULT NULL,
			       P_WHR	    IN VARCHAR2 DEFAULT NULL)
	RETURN CLOB;
    FUNCTION GET_RCPTS(P_DOC_SRL IN POS_GNR_RCPTS.DOC_SRL%TYPE DEFAULT NULL) RETURN CLOB;
    FUNCTION GET_EXPNS(P_DOC_SRL IN POS_GNR_EXPNS.DOC_SRL%TYPE DEFAULT NULL) RETURN CLOB;
    FUNCTION GET_XML_QRY (P_QRY_STR IN VARCHAR2,P_ROW_TAG_NM VARCHAR2)	RETURN CLOB;
    FUNCTION GET_CSTMRS(P_LANG_NO    IN IAS_LABELS.LANG_NO%TYPE,
			P_CUR_CODE   IN POS_GNR_RCPTS.CUR_CODE%TYPE,
			P_USR_NO     IN USER_R.U_ID%TYPE)      RETURN CLOB;
END POS_RCPTS_EXPNS_API_PKG;
/

-- ---------------------------------------------
-- PACKAGE BODY: POS_RCPTS_EXPNS_API_PKG  (status: INVALID)
-- ---------------------------------------------
CREATE OR REPLACE
PACKAGE BODY POS_RCPTS_EXPNS_API_PKG
IS
    FUNCTION GET_SQLERRM
	RETURN VARCHAR2
    IS
	L_GET_SQLERRM VARCHAR2(2000) := SQLERRM;
    BEGIN
	RETURN REPLACE(L_GET_SQLERRM,'"','');
    END GET_SQLERRM;
--#----------------------------------------------------------------------------------------------------------#--
    FUNCTION PST_COMMIT_PRC
	RETURN VARCHAR2
    IS
    BEGIN
	RETURN NULL;
    EXCEPTION
	WHEN NO_DATA_FOUND THEN
	    RETURN GET_SQLERRM;
    END PST_COMMIT_PRC;
--#----------------------------------------------------------------------------------------------------------#--
	 FUNCTION LOAD_PRMTRS  RETURN VARCHAR2 IS
	   BEGIN
	     BEGIN
	     SELECT  USE_WRK_SHFT
		INTO G_USE_WRK_SHFT
	       FROM IAS_PARA_POS;
	       RETURN NULL;
	     EXCEPTION WHEN OTHERS  THEN
		    RETURN 'ERROR WHEN GET PARAMETERS FROM IAS_PARA_POS ' || SQLERRM;
	     END;
	 END LOAD_PRMTRS;
--##-----------------------------------------------------------------------------------------------------##--
    FUNCTION GET_PYMNT_TYPE (P_LANG_NO IN IAS_LABELS.LANG_NO%TYPE,
			     P_USR_NO  IN USER_R.U_ID%TYPE DEFAULT NULL) RETURN CLOB
    IS
    BEGIN
	IF P_USR_NO IS NOT NULL THEN
	    V_WHR:=' AND D.U_ID='|| P_USR_NO;
	END IF;
	RETURN POS_RCPTS_EXPNS_API_PKG.GET_XML_QRY(P_QRY_STR =>'SELECT M.FLG_SR||''-''||M.FLG_DESC FLG_NM,TO_CHAR(M.FLG_VALUE) FLG_VAL,D.U_ID ,D.PRIV_FLAG
						      FROM S_FLAGS M,S_FLAGS_PRIV D
						     WHERE M.FLG_CODE=D.FLG_CODE AND M.FLG_VALUE=D.FLG_VALUE
						       AND UPPER(M.FLG_CODE)  =  ''PAY_TYPE_NAME_POS''
						       AND M.FLG_VALUE IN(1,4)
						       AND M.LANG_NO ='||P_LANG_NO||V_WHR||'
						  ORDER BY D.U_ID,M.FLG_SR ',

				       P_ROW_TAG_NM => 'JV_TYPE');

    EXCEPTION
	WHEN OTHERS
	THEN
	    RETURN '{"_Result": {"_ErrMsg":"ERROR IN GET_JV_TYPE ' || GET_SQLERRM || '","_ErrNo":-1 } }';
    END GET_PYMNT_TYPE;
--#----------------------------------------------------------------------------------------------------------#--
    FUNCTION GET_CRRNCS (P_LANG_NO IN IAS_LABELS.LANG_NO%TYPE) RETURN CLOB
    IS
    BEGIN

	RETURN POS_RCPTS_EXPNS_API_PKG.GET_XML_QRY(P_QRY_STR =>'SELECT CUR_CODE ,CUR_NO||'' - ''||CUR_CODE||''	''||DECODE('||P_LANG_NO||',1,CUR_NAME,CUR_E_NAME) CUR_NM,
							   IAS_GEN_PKG.GET_CUR_RATE(P_ACY=>CUR_CODE) CUR_RATE
						      FROM EX_RATE ORDER BY CUR_NO',
				       P_ROW_TAG_NM => 'CUR_CODE');

    EXCEPTION
	WHEN OTHERS
	THEN
	    RETURN '{"_Result": {"_ErrMsg":"ERROR IN GET_CRNCY ' || GET_SQLERRM || '","_ErrNo":-2 } }';
    END GET_CRRNCS;
--#----------------------------------------------------------------------------------------------------------#--
    FUNCTION GET_CR_CARD_TYPES (P_LANG_NO IN IAS_LABELS.LANG_NO%TYPE) RETURN CLOB
    IS
    BEGIN

	RETURN POS_RCPTS_EXPNS_API_PKG.GET_XML_QRY(P_QRY_STR => 'SELECT  CR_CARD_TYPE||''-''||DECODE('||P_LANG_NO||',1,NVL(CARD_A_NAME, CARD_E_NAME),NVL(CARD_E_NAME,CARD_A_NAME)) CR_CARD_TYPE_NM,
							     CR_CARD_TYPE CR_CARD_TYPE
						       FROM  IAS_CR_CARD_TYPES
						   ORDER BY  CR_CARD_TYPE',
				       P_ROW_TAG_NM => 'CR_CARD_TYPE');

    EXCEPTION
	WHEN OTHERS
	THEN
	    RETURN '{"_Result": {"_ErrMsg":"ERROR IN GET_CR_CARD_TYPES ' || GET_SQLERRM || '","_ErrNo":-3 } }';
    END GET_CR_CARD_TYPES;
--#----------------------------------------------------------------------------------------------------------#--
    FUNCTION GET_BNK(P_LANG_NO	IN IAS_LABELS.LANG_NO%TYPE,
		       P_USR_NO   IN USER_R.U_ID%TYPE) RETURN CLOB
    IS
    BEGIN

	RETURN POS_RCPTS_EXPNS_API_PKG.GET_XML_QRY(P_QRY_STR => 'SELECT BANK_NO,BANK_NO||''-''|| DECODE('||P_LANG_NO||',1,NVL(BANK_NAME,BANK_E_NAME),NVL(BANK_E_NAME,BANK_NAME)) BANK_NM
						       FROM CASH_AT_BANK
						      WHERE EXISTS
								 (SELECT 1
								    FROM PRIV_CASH
								   WHERE CASH_AT_BANK.BANK_NO = PRIV_CASH.CASH_NO
									 AND CASH_TYPE = 2
									 AND U_ID = '||P_USR_NO||'
									 AND NVL (ADD_FLAG, 0) = 1
									 AND ROWNUM <= 1)
						    ORDER BY BANK_NO',
				       P_ROW_TAG_NM => 'BANK_NO');
    EXCEPTION
	WHEN OTHERS
	THEN
	    RETURN '{"_Result": {"_ErrMsg":"ERROR IN GET BANKS ' || GET_SQLERRM || '","_ErrNo":-5 } }';
    END GET_BNK;
--#----------------------------------------------------------------------------------------------------------#--
    FUNCTION GET_CRDT_CRDS(P_LANG_NO  IN IAS_LABELS.LANG_NO%TYPE,
			   P_TRMNL_NO IN IAS_POS_BILL_MST.MACHINE_NO%TYPE) RETURN CLOB
    IS
    BEGIN


      --  RETURN GET_CRDT_CRDS (P_LANG_NO,P_TRMNL_NO);
      NULL;

    EXCEPTION
	WHEN OTHERS
	THEN
	    RETURN '{"_Result": {"_ErrMsg":"ERROR IN GET_CR_CARDS ' || GET_SQLERRM || '","_ErrNo":-6 } }';
    END GET_CRDT_CRDS;
--#----------------------------------------------------------------------------------------------------------#--
    FUNCTION GET_CSTMR_ORDRS(P_LANG_NO	 IN IAS_LABELS.LANG_NO%TYPE,
			     P_USR_NO	 IN USER_R.U_ID%TYPE,
			     P_ORDER_SER IN SALES_ORDER.ORDER_SER%TYPE	DEFAULT NULL  ) RETURN CLOB
    IS
     V_WHR   VARCHAR2(100) :=NULL;
    BEGIN

       IF P_ORDER_SER IS NOT NULL THEN
	    V_WHR := ' AND ORDER_SER = '||P_ORDER_SER;
       END IF;
       RETURN POS_RCPTS_EXPNS_API_PKG.GET_XML_QRY(P_QRY_STR => 'SELECT SO_TYPE,
							       ORDER_NO,
							       ORDER_SER,
							       ORDER_DATE,
							       ORDER_TIME,
							       QUOT_NO,
							       QUOT_SER,
							       ORDER_CUR,
							       CUR_RATE,
							       C_CODE,
							       C_NAME,
							       A_DESC,
							       CC_CODE,
							       PJ_NO,
							       ACTV_NO,
							       W_CODE,
							       REP_CODE,
							       PROCESED,
							       STAND_BY,
							       LOADED,
							       REF_DOC_NO,
							       REF_DOC_DATE,
							       DISC_AMT,
							       DISC_AMT_MST,
							       DISC_AMT_DTL,
							       APPROVED,
							       APRV_U_ID,
							       APRV_DATE,
							       APRV_DSC,
							       PREPARE_DATE,
							       REC_DEALER_DATE,
							       DELIVERY_DATE,
							       REPEAT_USE_IN_BILLS,
							       INACTIVE,
							       INACTIVE_RES,
							       INACTIVE_DATE,
							       INACTIVE_U_ID,
							       PAPER_NO,
							       PAPER_SERIAL,
							       R_CODE,
							       PRM_CODE,
							       DRIVER_NO,
							       BILL_DOC_TYPE,
							       BILL_DUE_DATE,
							       ORDER_EXPIRE_DATE,
							       CHEQUE_DUE_DATE,
							       EXTERNAL_POST,
							       PROCESS_INC_FLG,
							       APPROVED_SALES_MNG,
							       APRV_SALES_MNG_U_ID,
							       APRV_SALES_MNG_DATE,
							       TRANSFER_PRODUCT,
							       VAT_AMT,
							       ORDER_AMT,
							       EMP_NO,
							       OTHR_AMT,
							       SI_TYPE,
							       FIELD1,
							       FIELD2,
							       FIELD3,
							       FIELD4,
							       FIELD5,
							       FIELD6,
							       FIELD7,
							       FIELD8,
							       FIELD9,
							       FIELD10,
							       AD_U_ID,
							       AD_DATE,
							       UP_U_ID,
							       UP_DATE,
							       UP_CNT,
							       PR_REP,
							       CMP_NO,
							       BRN_NO,
							       BRN_YEAR,
							       BRN_USR,
							       DISC_AMT_MST_VAT,
							       MACHINE_NO,
							       CUST_CODE,
							       MOBILE_NO,
							       PYMNT_TYPE,
							       CASH_NO,
							       CSH_PYMNT_AMT,
							       CREDIT_CARD,
							       CR_CARD_NO,
							       CR_CARD_NO_SCND,
							       CR_CARD_NO_THRD,
							       CR_CARD_AMT,
							       CR_CARD_AMT_SCND,
							       CR_CARD_AMT_THRD,
							       CR_CARD_DSC,
							       CR_CARD_DSC_SCND,
							       CR_CARD_DSC_THRD,
							       CR_BANK_NO,
							       CR_BANK_NO_SCND,
							       CR_BANK_NO_THRD,
							       CR_DOC_NO_REF,
							       CR_DOC_NO_REF_SCND,
							       CR_DOC_NO_REF_THRD,
							       CR_CARD_COMM_PER,
							       CR_CARD_COMM_PER_SCND,
							       CR_CARD_COMM_PER_THRD,
							       CR_CARD_CST_NO,
							       CR_CARD_CST_NO_SCND,
							       CR_CARD_CST_NO_THRD,
							       ADVNC_PYMNT_A_CODE,
							       ADVNC_PYMNT_AC_CODE_DTL,
							       ADVNC_PYMNT_AC_DTL_TYP,
							       SYS_DOC_ID,
							       SHFT_SRL,
							       DOC_SER_EXTRNL
							FROM SALES_ORDER
						       WHERE NVL(PROCESED,0) = 0
							  '||V_WHR||'
							 AND (('||P_USR_NO||' = 1)
								  OR EXISTS(
									SELECT 1
									  FROM S_BRN_USR_PRIV
									 WHERE U_ID = '||P_USR_NO||'
									   AND S_BRN_USR_PRIV.BRN_NO = SALES_ORDER.BRN_NO
									   AND NVL(FILL_FLAG, 1) = 1
									   AND ROWNUM <= 1))
						    ORDER BY ORDER_NO,ORDER_DATE',
				       P_ROW_TAG_NM => 'ORDR_NO');

    EXCEPTION
	WHEN OTHERS
	THEN
	    RETURN '{"_Result": {"_ErrMsg":"ERROR IN GET_RSRVS ' || GET_SQLERRM || '","_ErrNo":-7 } }';
    END GET_CSTMR_ORDRS;
    FUNCTION GET_CSTMR_ORDRS_LST(P_LANG_NO   IN IAS_LABELS.LANG_NO%TYPE,
				 P_USR_NO    IN USER_R.U_ID%TYPE,
				 P_ORDER_SER IN SALES_ORDER.ORDER_SER%TYPE  DEFAULT NULL,
				 P_WHR	     IN VARCHAR2 DEFAULT NULL  ) RETURN CLOB
    IS
     V_WHR   VARCHAR2(100) :=NULL;
    BEGIN
       IF P_ORDER_SER IS NOT NULL THEN
	    V_WHR := ' AND ORDER_SER = '||P_ORDER_SER;
       END IF;
       V_WHR:=V_WHR||' '||P_WHR;
       RETURN POS_RCPTS_EXPNS_API_PKG.GET_XML_QRY(P_QRY_STR => 'SELECT SO_TYPE,
							       ORDER_NO,
							       ORDER_SER,
							       ORDER_DATE,
							       ORDER_CUR,
							       CUR_RATE,
							       C_CODE,
							       C_NAME,
							       CUST_CODE,
							       MOBILE_NO,
							       A_DESC,
							       NVL(ORDER_AMT,0)+NVL(VAT_AMT,0)-NVL(DISC_AMT,0) NET_ORDER_AMT,
							       PROCESED,
							       INACTIVE,
							       PYMNT_TYPE,
							       ADVNC_PYMNT_AC_DTL_TYP,
							       ADVNC_PYMNT_A_CODE,
							       ADVNC_PYMNT_AC_CODE_DTL,
							       CSH_PYMNT_AMT CSH_PYMNT_AMT,
							       NVL(CR_CARD_AMT,0)+NVL(CR_CARD_AMT_SCND,0)+NVL(CR_CARD_AMT_THRD,0) CR_CARD_PYMNT_AMT,
							       (NVL(ORDER_AMT,0)+NVL(VAT_AMT,0)-NVL(DISC_AMT,0))
							       -(NVL(CSH_PYMNT_AMT,0)+ NVL(CR_CARD_AMT,0)+NVL(CR_CARD_AMT_SCND,0)+NVL(CR_CARD_AMT_THRD,0) )
							       ADVNC_RMN_AMT
							FROM SALES_ORDER
						       WHERE NVL(INACTIVE,0) = 0
						       --AND ADVNC_PYMNT_A_CODE IS NOT NULL
							  '||V_WHR||'
							 AND (('||P_USR_NO||' = 1)
								  OR EXISTS(
									SELECT 1
									  FROM S_BRN_USR_PRIV
									 WHERE U_ID = '||P_USR_NO||'
									   AND S_BRN_USR_PRIV.BRN_NO = SALES_ORDER.BRN_NO
									   AND NVL(FILL_FLAG, 1) = 1
									   AND ROWNUM <= 1))
						    ORDER BY ORDER_NO,ORDER_DATE',
				       P_ROW_TAG_NM => 'ORDR_NO');
    EXCEPTION
	WHEN OTHERS
	THEN
	    RETURN '{"_Result": {"_ErrMsg":"ERROR IN GET_ORDER_LST ' || GET_SQLERRM || '","_ErrNo":-7 } }';
    END GET_CSTMR_ORDRS_LST;
--#----------------------------------------------------------------------------------------------------------#--
     FUNCTION INSRT_RCPTS(P_XML_INPT IN CLOB,P_ONLINE_FLG NUMBER) RETURN VARCHAR2
    IS
	L_XML_INPT	 XMLTYPE := XMLTYPE.CREATEXML(P_XML_INPT);
	L_ERR_MSG	 VARCHAR2(2000);
	L_JSON_RSLT	 VARCHAR2(2000);
	L_ROW_INSRTD BOOLEAN := FALSE;
	L_DOC_DATE	 POS_GNR_RCPTS.DOC_DATE%TYPE;
	V_CNT		 NUMBER;
	V_PRVS_AMT	 NUMBER;
	V_ORDR_AMT	 NUMBER;
	V_ERR_TXT	 VARCHAR2(2000);

	FUNCTION GET_ERR_FNC(P_LBL_NO NUMBER DEFAULT NULL,P_MSG_NO NUMBER  DEFAULT NULL,P_MSG_TXT VARCHAR2  DEFAULT NULL)
	    RETURN VARCHAR2
	IS
	    L_ERR_TXT VARCHAR2(2000) := NULL;
	BEGIN
	    IF P_MSG_NO IS NOT NULL AND P_LBL_NO IS NOT NULL THEN
		L_ERR_TXT := 'MSG_NO:' || P_MSG_NO || ' - ' || IAS_GEN_PKG.GET_MSG(P_LNG_NO => G_LNG_NO, P_MSG_NO => P_MSG_NO) || ' - ' || IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => P_LBL_NO) || ' ' || P_MSG_TXT;
	    ELSIF P_MSG_NO IS NOT NULL THEN
		L_ERR_TXT :=  'MSG_NO:' || P_MSG_NO || ' - ' || IAS_GEN_PKG.GET_MSG(P_LNG_NO => G_LNG_NO, P_MSG_NO => P_MSG_NO) || ' ' || P_MSG_TXT;
	    END IF;

	    ROLLBACK;
	    RETURN '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"' || REPLACE(L_ERR_TXT,'"','') || '","_ErrNo":-70 } }';

	END GET_ERR_FNC;


    BEGIN
	FOR MST_CRSR IN (SELECT EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_NO') AS DOC_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_SRL') AS DOC_SRL,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_TYPE') AS DOC_TYPE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_DATE') AS DOC_DATE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_TIME') AS DOC_TIME,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/REF_NO') AS REF_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CUR_CODE') AS CUR_CODE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/EX_RATE') AS EX_RATE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_AMT') AS DOC_AMT,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_DSC') AS DOC_DSC,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CASH_NO') AS CASH_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/MACHINE_NO') AS MACHINE_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/PYMNT_TYPE') AS PYMNT_TYPE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/EXTRNL_PST') AS EXTRNL_PST,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/A_CODE') AS A_CODE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/AC_CODE_DTL') AS AC_CODE_DTL,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/AC_DTL_TYP') AS AC_DTL_TYP,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CR_CARD_TYPE') AS CR_CARD_TYPE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CR_CARD_NO') AS CR_CARD_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CR_CARD_COMM_PER') AS CR_CARD_COMM_PER,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CR_CARD_DSC') AS CR_CARD_DSC,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CR_CARD_NO_REF') AS CR_CARD_NO_REF,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/MOBILE_NO') AS MOBILE_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CUST_CODE') AS CUST_CODE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CC_CODE') AS CC_CODE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/PJ_NO') AS PJ_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/ACTV_NO') AS ACTV_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CHQ_NO') AS CHQ_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/BNK_NO') AS BNK_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/PRCSS_FLG') AS PRCSS_FLG,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/AD_U_ID') AS AD_U_ID,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/AD_DATE') AS AD_DATE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/AD_TRMNL_NM') AS AD_TRMNL_NM,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_NO_REF') AS DOC_NO_REF,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_SRL_REF') AS DOC_SRL_REF,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_TYP_REF') AS DOC_TYP_REF,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/SHFT_SRL') AS SHFT_SRL,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/BRN_NO') AS BRN_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/BRN_YEAR') AS BRN_YEAR,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/BRN_USR') AS BRN_USR,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CMP_NO') AS CMP_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/LNG_NO') AS LNG_NO
			   FROM TABLE(XMLSEQUENCE(EXTRACT(L_XML_INPT, '/POS_RCPTS/POS_GNR_RCPTS'))) XMLMSTDMY)
	LOOP

       V_ERR_MSG := LOAD_PRMTRS;
	IF V_ERR_MSG IS NOT NULL THEN
	    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 670,P_MSG_TXT =>V_ERR_MSG);
	END IF;

	    G_DOC_NO := MST_CRSR.DOC_NO;
	    G_DOC_SRL := MST_CRSR.DOC_SRL;
	    G_LNG_NO := NVL(MST_CRSR.LNG_NO,1);
	    G_TRMNL_NO := MST_CRSR.MACHINE_NO;
	    G_CMP_NO := MST_CRSR.CMP_NO;
	    G_BRN_NO := MST_CRSR.BRN_NO;
	    G_BRN_YEAR := TO_CHAR(YS_GEN_PKG.GET_CURDATE, 'YYYY');
	    G_BRN_USR := MST_CRSR.BRN_USR;
	    G_USR_NO := MST_CRSR.AD_U_ID;
	    G_CASH_NO:= MST_CRSR.CASH_NO;
	    G_AD_DATE := YS_GEN_PKG.GET_CURDATE;

	    G_LBL_NO := NULL;
	    G_MSG_NO := NULL;
	    G_MSG_TXT := NULL;

	    IF	MST_CRSR.DOC_DATE IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_DATE');
	    END IF;
	    IF	MST_CRSR.DOC_TIME IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_TIME');
	    END IF;
	    IF G_BRN_NO IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'BRN_NO');
	    END IF;

	    IF G_CMP_NO IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'CMP_NO');
	    END IF;

	    IF G_BRN_USR IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'BRN_USR');
	    END IF;

	    IF G_BRN_YEAR IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'BRN_YEAR');
	    END IF;

	    IF G_USR_NO IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'AD_U_ID');
	    END IF;

	    IF MST_CRSR.PYMNT_TYPE IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'PYMNT_TYPE');
	    END IF;
	    IF MST_CRSR.DOC_TYPE IS NULL OR MST_CRSR.DOC_TYPE NOT IN (1,2) THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 6599,P_MSG_TXT => 'DOC_TYPE');
	    END IF;

	    IF MST_CRSR.CUR_CODE IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'CUR_CODE');
	    END IF;

	    IF NVL(MST_CRSR.DOC_AMT,0) = 0 THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 506,P_MSG_TXT => 'DOC_AMT');
	    END IF;

	    IF MST_CRSR.A_CODE IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => 4540,P_MSG_NO => 644,P_MSG_TXT => 'A_CODE');
	    END IF;

	    IF MST_CRSR.DOC_DSC IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_DSC');
	    END IF;

	    IF MST_CRSR.EX_RATE IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'EX_RATE');
	    END IF;

	    IF G_TRMNL_NO IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => 4540,P_MSG_NO => 644,P_MSG_TXT => '');
	    END IF;
	    IF	NVL(G_USE_WRK_SHFT,0)>1  AND MST_CRSR.SHFT_SRL IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => 11633,P_MSG_NO => 644,P_MSG_TXT => 'SHFT_SRL');
	    END IF;

	    IF G_CASH_NO IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'CASH_NO');
	    END IF;


	    G_SRVR_NO :=POS_GNR_PKG.GET_SRVR_NO_FNC;
	    L_DOC_DATE := TO_CHAR(SYSDATE,'DD/MM/YYYY');

	   IF NVL(P_ONLINE_FLG,0)>0 THEN
		    --##GENERATE DOC_NO AND DOC_SRL
		    BEGIN
			SELECT NVL(MAX(DOC_NO),0)+1
			  INTO G_DOC_NO
			  FROM POS_GNR_RCPTS
			 WHERE BRN_NO	= G_BRN_NO
			   AND MACHINE_NO = G_TRMNL_NO	;
		    EXCEPTION
			WHEN OTHERS THEN
			    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 297,P_MSG_TXT => 'DOC_NO');
		    END;
		    G_DOC_SRL := G_BRN_YEAR||LPAD(G_BRN_NO,6,'0')||LPAD(G_SRVR_NO,3,0)||170||LPAD(G_TRMNL_NO,5,0)||G_DOC_NO;
	   ELSE
	       IF G_DOC_NO IS NULL THEN
		   RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_NO');
	       END IF;
	       IF G_DOC_SRL IS NULL THEN
		   RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_SRL');
	       END IF;
	       BEGIN
		    SELECT COUNT(1)
		      INTO V_CNT
		    FROM POS_GNR_RCPTS
		      WHERE DOC_SRL = G_DOC_SRL  AND ROWNUM <=1;
		EXCEPTION WHEN OTHERS THEN
		    V_CNT:=0;
		END;
		IF NVL(V_CNT,0)>0 THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 8,P_MSG_TXT => 'DOC_SRL='||G_DOC_SRL);
		END IF;
	    END IF;

	    IF MST_CRSR.PYMNT_TYPE = 4 THEN
		IF MST_CRSR.CR_CARD_TYPE IS NULL THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'CR_CARD_TYPE');
		END IF;

		--# check if CR_CARD_TYPE is there
		BEGIN
		    SELECT  1 INTO V_CNT
			      FROM IAS_CR_CARD_TYPES
			     WHERE CR_CARD_TYPE = MST_CRSR.CR_CARD_TYPE
			       AND ROWNUM <=1 ;
		EXCEPTION
		    WHEN OTHERS THEN
			V_CNT := 0;
		END;

		IF V_CNT = 0 THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 4847,P_MSG_TXT => 'CR_CARD_TYPE');
		END IF;

		IF MST_CRSR.CR_CARD_NO IS NULL THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'CR_CARD_NO');
		END IF;

		--# check if CR_CARD_NO is there
		BEGIN
		    SELECT 1 INTO V_CNT
			     FROM CREDIT_CARD_TYPES
			    WHERE MACHINE_NO   = G_TRMNL_NO
			      AND CR_CARD_TYPE = MST_CRSR.CR_CARD_TYPE
			      AND CR_CARD_NO   = MST_CRSR.CR_CARD_NO
			      AND ROWNUM <=1;
		EXCEPTION
		    WHEN OTHERS THEN
			V_CNT := 0;
		END;

		IF V_CNT = 0 THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 1488,P_MSG_TXT => 'CR_CARD_NO');
		END IF;

		IF MST_CRSR.CR_CARD_NO_REF IS NULL THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'CR_CARD_NO_REF');
		END IF;
	    ELSIF MST_CRSR.PYMNT_TYPE = 6 THEN
		IF MST_CRSR.BNK_NO IS NULL THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'BNK_NO');
		END IF;
		--# check if bank is there
		BEGIN
		    SELECT 1 INTO V_CNT
			     FROM CASH_AT_BANK
			    WHERE BANK_NO = MST_CRSR.BNK_NO;

		EXCEPTION
		    WHEN OTHERS THEN
			V_CNT := 0;
		END;

		IF V_CNT = 0 THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 600,P_MSG_TXT => 'BNK_NO');
		END IF;

		--# check if privilage of bank
		BEGIN
		    SELECT 1 INTO V_CNT
			     FROM CASH_AT_BANK
			    WHERE EXISTS( SELECT 1
					    FROM PRIV_CASH
					   WHERE CASH_AT_BANK.BANK_NO = PRIV_CASH.CASH_NO
					     AND CASH_TYPE = 2
					     AND U_ID = G_USR_NO
					     AND A_CY = MST_CRSR.CUR_CODE
					     AND NVL (ADD_FLAG, 0) = 1
					     AND ROWNUM <= 1)
			      AND BANK_NO =MST_CRSR.BNK_NO;

		EXCEPTION
		    WHEN OTHERS THEN
			V_CNT := 0;
		END;

		IF V_CNT = 0 THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 6794,P_MSG_TXT => MST_CRSR.BNK_NO);
		END IF;

		IF MST_CRSR.CHQ_NO IS NULL THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'CHQ_NO');
		END IF;
	    END IF;

	    IF MST_CRSR.DOC_NO_REF IS NOT NULL THEN
		IF MST_CRSR.DOC_SRL_REF IS NULL THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_SRL_REF');
		END IF;

		/*IF MST_CRSR.DOC_TYP_REF IS NULL THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_TYP_REF');
		END IF;*/
	    END IF;

	    IF MST_CRSR.DOC_SRL_REF IS NOT NULL THEN
		IF MST_CRSR.DOC_NO_REF IS NULL THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_NO_REF');
		END IF;

	       /* IF MST_CRSR.DOC_TYP_REF IS NULL THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_TYP_REF');
		END IF;*/
	    END IF;

	    IF MST_CRSR.DOC_SRL_REF IS NOT NULL AND NVL(MST_CRSR.DOC_AMT,0) > 0 THEN
		--# GET ORDR_AMT
		BEGIN
		    SELECT NVL(ORDER_AMT,0)
		      INTO V_ORDR_AMT
		      FROM SALES_ORDER
		     WHERE ORDER_SER = MST_CRSR.DOC_SRL_REF
		       AND ROWNUM <= 1;

		EXCEPTION
		  WHEN OTHERS THEN
		     V_ORDR_AMT := 0;
		END;
		IF  NVL(MST_CRSR.DOC_AMT,0) >  NVL(V_ORDR_AMT,0) THEN
		    V_ERR_TXT :=  'MSG_NO:' || 296||CHR (13) || ' - ' || IAS_GEN_PKG.GET_MSG(P_LNG_NO => G_LNG_NO, P_MSG_NO => 296)
								 || ' ' || IAS_GEN_PKG.GET_PROMPT (G_LNG_NO, 1217)
								 || '='
								 || (NVL(MST_CRSR.DOC_AMT,0))
								 || CHR (13)
								 || IAS_GEN_PKG.GET_PROMPT (G_LNG_NO, 1818)
								 || '='
								 || V_ORDR_AMT;
		    RETURN '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"' || REPLACE(V_ERR_TXT,'"','') || '","_ErrNo":-8 } }';

		END IF;


	    END IF;

	    --##CHK AC_CODE_DTL
	    IF MST_CRSR.AC_CODE_DTL IS NOT NULL THEN
		IF NVL(MST_CRSR.AC_DTL_TYP,0) = 3 THEN
		    BEGIN
			SELECT 1 INTO V_CNT
				 FROM CUSTOMER,ACCOUNT
				WHERE ACCOUNT.A_CODE =CUSTOMER.C_A_CODE
				  AND NVL (INACTIVE, 0)  =0
				  AND CUSTOMER.C_A_CODE  =MST_CRSR.A_CODE
				  AND CUSTOMER.C_CODE	 =MST_CRSR.AC_CODE_DTL
				  AND ACCOUNT.AC_DTL_TYP =MST_CRSR.AC_DTL_TYP
				  AND ACCOUNT.AC_DTL_TYP =3
				  AND ROWNUM <=1;
		    EXCEPTION
			WHEN OTHERS THEN
			    V_CNT := 0;
		    END;
		    IF V_CNT = 0 THEN
			Begin
			SELECT 1 INTO V_CNT FROM IAS_CST_ACCNT
			WHERE C_CODE  =MST_CRSR.AC_CODE_DTL
			AND AC_TYP=3
			AND ROWNUM <=1;
			EXCEPTION WHEN OTHERS THEN
			    V_CNT := 0;
			END;
			IF NVL(V_CNT,0) = 0 THEN
			  RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 3,P_MSG_TXT => '');
			END IF;
		    END IF;
		END IF;
	    ELSIF MST_CRSR.AC_CODE_DTL IS NULL AND NVL(MST_CRSR.AC_DTL_TYP,0)<>0 THEN
		   RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 4559,P_MSG_TXT => '');
	    END IF;

	    --##INSERT DATA
	    BEGIN
		INSERT INTO POS_GNR_RCPTS( DOC_NO
					  ,DOC_SRL
					  ,DOC_TYPE
					  ,DOC_DATE
					  ,DOC_TIME
					  ,REF_NO
					  ,CUR_CODE
					  ,EX_RATE
					  ,DOC_AMT
					  ,DOC_DSC
					  ,CASH_NO
					  ,MACHINE_NO
					  ,EXTRNL_PST
					  ,PYMNT_TYPE
					  ,A_CODE
					  ,AC_CODE_DTL
					  ,AC_DTL_TYP
					  ,CR_CARD_TYPE
					  ,CR_CARD_NO
					  ,CR_CARD_COMM_PER
					  ,CR_CARD_DSC
					  ,CR_CARD_NO_REF
					  ,MOBILE_NO
					  ,CUST_CODE
					  ,CC_CODE
					  ,PJ_NO
					  ,ACTV_NO
					  ,CHQ_NO
					  ,BNK_NO
					  ,PST_FLG
					  ,PRCSS_FLG
					  ,AD_U_ID
					  ,AD_DATE
					  ,AD_TRMNL_NM
					  ,DOC_NO_REF
					  ,DOC_SRL_REF
					  ,DOC_TYP_REF
					  ,SHFT_SRL
					  ,BRN_NO
					  ,BRN_YEAR
					  ,BRN_USR
					  ,CMP_NO)
		       VALUES (G_DOC_NO
			      ,G_DOC_SRL
			      ,MST_CRSR.DOC_TYPE
			      ,L_DOC_DATE
			      ,MST_CRSR.DOC_TIME
			      ,MST_CRSR.REF_NO
			      ,MST_CRSR.CUR_CODE
			      ,MST_CRSR.EX_RATE
			      ,NVL(MST_CRSR.DOC_AMT,0)
			      ,MST_CRSR.DOC_DSC
			      ,G_CASH_NO
			      ,G_TRMNL_NO
			      ,NVL(MST_CRSR.EXTRNL_PST,0)
			      ,MST_CRSR.PYMNT_TYPE
			      ,MST_CRSR.A_CODE
			      ,MST_CRSR.AC_CODE_DTL
			      ,MST_CRSR.AC_DTL_TYP
			      ,MST_CRSR.CR_CARD_TYPE
			      ,MST_CRSR.CR_CARD_NO
			      ,MST_CRSR.CR_CARD_COMM_PER
			      ,MST_CRSR.CR_CARD_DSC
			      ,MST_CRSR.CR_CARD_NO_REF
			      ,MST_CRSR.MOBILE_NO
			      ,MST_CRSR.CUST_CODE
			      ,MST_CRSR.CC_CODE
			      ,MST_CRSR.PJ_NO
			      ,MST_CRSR.ACTV_NO
			      ,MST_CRSR.CHQ_NO
			      ,MST_CRSR.BNK_NO
			      ,NVL(MST_CRSR.PRCSS_FLG,0)
			      ,0
			      ,G_USR_NO
			      ,G_AD_DATE
			      ,MST_CRSR.AD_TRMNL_NM
			      ,MST_CRSR.DOC_NO_REF
			      ,MST_CRSR.DOC_SRL_REF
			      ,MST_CRSR.DOC_TYP_REF
			      ,MST_CRSR.SHFT_SRL
			      ,G_BRN_NO
			      ,G_BRN_YEAR
			      ,G_BRN_USR
			      ,G_CMP_NO);

			      L_ROW_INSRTD := TRUE;
	    EXCEPTION
		WHEN OTHERS THEN
		    ROLLBACK;
		    RETURN '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"ERROR WHEN INSERT INTO POS_GNR_RCPTS ' || GET_SQLERRM || '","_ErrNo":-9 } }';
	    END;


	END LOOP;

	IF G_DOC_NO IS NOT NULL AND G_DOC_SRL IS NOT NULL THEN

	    IF L_ROW_INSRTD THEN
		L_ERR_MSG := PST_COMMIT_PRC;

		IF L_ERR_MSG IS NOT NULL THEN
		    L_JSON_RSLT := '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"' || REPLACE(L_ERR_MSG,'"','') || '","_ErrNo":-10 } }';
		END IF;
	    ELSE
		L_JSON_RSLT := '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"NO DATA INSERTED","_ErrNo":-11 } }';
	    END IF;


	ELSE
	    L_JSON_RSLT := '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"NO DATA INSERTED","_ErrNo":-12 } }';
	END IF;

	IF L_JSON_RSLT IS NULL THEN
	    COMMIT;
	    L_JSON_RSLT := '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"SUCCESSFUL","_ErrNo":0 } }';
	ELSE
	    ROLLBACK;
	END IF;

	RETURN L_JSON_RSLT;

    EXCEPTION
	WHEN OTHERS THEN
	    ROLLBACK;
	    RETURN '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"ERROR IN INSRT_RCPTS_CNTS ' || GET_SQLERRM || '","_ErrNo":-13 } }';
    END INSRT_RCPTS;
--#----------------------------------------------------------------------------------------------------------#--
 FUNCTION INSRT_EXPNS(P_XML_INPT IN CLOB,P_ONLINE_FLG NUMBER) RETURN VARCHAR2
    IS
	L_XML_INPT	 XMLTYPE := XMLTYPE.CREATEXML(P_XML_INPT);
	L_ERR_MSG	 VARCHAR2(2000);
	L_JSON_RSLT	 VARCHAR2(2000);
	L_ROW_INSRTD BOOLEAN := FALSE;
	L_DOC_DATE	 POS_GNR_EXPNS.DOC_DATE%TYPE;
	V_CNT		 NUMBER;
	V_PRVS_AMT	 NUMBER;
	V_ORDR_AMT	 NUMBER;
	V_ERR_TXT	 VARCHAR2(2000);

	FUNCTION GET_ERR_FNC(P_LBL_NO NUMBER DEFAULT NULL,P_MSG_NO NUMBER  DEFAULT NULL,P_MSG_TXT VARCHAR2  DEFAULT NULL)
	    RETURN VARCHAR2
	IS
	    L_ERR_TXT VARCHAR2(2000) := NULL;
	BEGIN
	    IF P_MSG_NO IS NOT NULL AND P_LBL_NO IS NOT NULL THEN
		L_ERR_TXT := 'MSG_NO:' || P_MSG_NO || ' - ' || IAS_GEN_PKG.GET_MSG(P_LNG_NO => G_LNG_NO, P_MSG_NO => P_MSG_NO) || ' - ' || IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => P_LBL_NO) || ' ' || P_MSG_TXT;
	    ELSIF P_MSG_NO IS NOT NULL THEN
		L_ERR_TXT :=  'MSG_NO:' || P_MSG_NO || ' - ' || IAS_GEN_PKG.GET_MSG(P_LNG_NO => G_LNG_NO, P_MSG_NO => P_MSG_NO) || ' ' || P_MSG_TXT;
	    END IF;

	    ROLLBACK;
	    RETURN '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"' || REPLACE(L_ERR_TXT,'"','') || '","_ErrNo":-70 } }';

	END GET_ERR_FNC;
    BEGIN

	FOR MST_CRSR IN (SELECT EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_NO') AS DOC_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_SRL') AS DOC_SRL,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_DATE') AS DOC_DATE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_TIME') AS DOC_TIME,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/REF_NO') AS REF_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CUR_CODE') AS CUR_CODE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/EX_RATE') AS EX_RATE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_AMT') AS DOC_AMT,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_DSC') AS DOC_DSC,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CASH_NO') AS CASH_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/MACHINE_NO') AS MACHINE_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/EXTRNL_PST') AS EXTRNL_PST,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/A_CODE') AS A_CODE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/AC_CODE_DTL') AS AC_CODE_DTL,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/AC_DTL_TYP') AS AC_DTL_TYP,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/MOBILE_NO') AS MOBILE_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CC_CODE') AS CC_CODE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/PJ_NO') AS PJ_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/ACTV_NO') AS ACTV_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/AD_U_ID') AS AD_U_ID,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/AD_DATE') AS AD_DATE,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/AD_TRMNL_NM') AS AD_TRMNL_NM,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_NO_REF') AS DOC_NO_REF,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_SRL_REF') AS DOC_SRL_REF,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/DOC_TYP_REF') AS DOC_TYP_REF,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/SHFT_SRL') AS SHFT_SRL,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/BRN_NO') AS BRN_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/BRN_YEAR') AS BRN_YEAR,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/BRN_USR') AS BRN_USR,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/CMP_NO') AS CMP_NO,
				EXTRACTVALUE (VALUE (XMLMSTDMY), '*/LNG_NO') AS LNG_NO
			   FROM TABLE(XMLSEQUENCE(EXTRACT(L_XML_INPT, '/POS_EXPNS/POS_GNR_EXPNS'))) XMLMSTDMY)
	LOOP
	    G_DOC_NO := MST_CRSR.DOC_NO;
	    G_DOC_SRL := MST_CRSR.DOC_SRL;
	    G_LNG_NO := NVL(MST_CRSR.LNG_NO,1);
	    G_TRMNL_NO := MST_CRSR.MACHINE_NO;
	    G_CMP_NO := MST_CRSR.CMP_NO;
	    G_BRN_NO := MST_CRSR.BRN_NO;
	    G_BRN_YEAR := TO_CHAR(YS_GEN_PKG.GET_CURDATE, 'YYYY');
	    G_BRN_USR := MST_CRSR.BRN_USR;
	    G_USR_NO := MST_CRSR.AD_U_ID;
	    G_CASH_NO:= MST_CRSR.CASH_NO;
	    G_AD_DATE := YS_GEN_PKG.GET_CURDATE;

	    G_LBL_NO := NULL;
	    G_MSG_NO := NULL;
	    G_MSG_TXT := NULL;

	    V_ERR_MSG := LOAD_PRMTRS;
	    IF V_ERR_MSG IS NOT NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 670,P_MSG_TXT =>V_ERR_MSG);
	    END IF;

	    IF	MST_CRSR.DOC_DATE IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_DATE');
	    END IF;
	    IF	MST_CRSR.DOC_TIME IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_TIME');
	    END IF;
	    IF G_BRN_NO IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'BRN_NO');
	    END IF;

	    IF G_CMP_NO IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'CMP_NO');
	    END IF;

	    IF G_BRN_USR IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'BRN_USR');
	    END IF;

	    IF G_BRN_YEAR IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'BRN_YEAR');
	    END IF;

	    IF G_USR_NO IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'AD_U_ID');
	    END IF;


	    IF MST_CRSR.CUR_CODE IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'CUR_CODE');
	    END IF;

	    IF NVL(MST_CRSR.DOC_AMT,0) = 0 THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 506,P_MSG_TXT => 'DOC_AMT');
	    END IF;

	    IF MST_CRSR.A_CODE IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => 4540,P_MSG_NO => 644,P_MSG_TXT => 'A_CODE');
	    END IF;

	    IF MST_CRSR.DOC_DSC IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_DSC');
	    END IF;

	    IF MST_CRSR.EX_RATE IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'EX_RATE');
	    END IF;

	    IF G_TRMNL_NO IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => 4540,P_MSG_NO => 644,P_MSG_TXT => '');
	    END IF;
	    IF G_CASH_NO IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'CASH_NO');
	    END IF;

	    IF	NVL(G_USE_WRK_SHFT,0)>1  AND MST_CRSR.SHFT_SRL IS NULL THEN
		RETURN GET_ERR_FNC(P_LBL_NO => 11633,P_MSG_NO => 644,P_MSG_TXT => 'SHFT_SRL');
	    END IF;

	    G_SRVR_NO :=POS_GNR_PKG.GET_SRVR_NO_FNC;
	    L_DOC_DATE := TO_CHAR(SYSDATE,'DD/MM/YYYY');
	   IF NVL(P_ONLINE_FLG,0)>0 THEN
	    --##GENERATE DOC_NO AND DOC_SRL
	    BEGIN
		SELECT NVL(MAX(DOC_NO),0)+1
		  INTO G_DOC_NO
		  FROM POS_GNR_EXPNS
		 WHERE BRN_NO	= G_BRN_NO
		   AND MACHINE_NO = G_TRMNL_NO	;
	    EXCEPTION
		WHEN OTHERS THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 297,P_MSG_TXT => 'DOC_NO');
	    END;

	    G_DOC_SRL := G_BRN_YEAR||LPAD(G_BRN_NO,6,'0')||LPAD(G_SRVR_NO,3,0)||171||LPAD(G_TRMNL_NO,5,0)||G_DOC_NO;
	  ELSE
	       IF G_DOC_NO IS NULL THEN
		   RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_NO');
	       END IF;
	       IF G_DOC_SRL IS NULL THEN
		   RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_SRL');
	       END IF;

	       BEGIN
		    SELECT COUNT(1)
		      INTO V_CNT
		    FROM POS_GNR_EXPNS
		      WHERE DOC_SRL = G_DOC_SRL  AND ROWNUM <=1;
		EXCEPTION WHEN OTHERS THEN
		    V_CNT:=0;
		END;
		IF NVL(V_CNT,0)>0 THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 8,P_MSG_TXT => 'DOC_SRL='||G_DOC_SRL);
		END IF;
	  END IF;

	    IF MST_CRSR.DOC_NO_REF IS NOT NULL THEN
		IF MST_CRSR.DOC_SRL_REF IS NULL THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_SRL_REF');
		END IF;

	    END IF;

	    IF MST_CRSR.DOC_SRL_REF IS NOT NULL THEN
		IF MST_CRSR.DOC_NO_REF IS NULL THEN
		    RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 644,P_MSG_TXT => 'DOC_NO_REF');
		END IF;
	    END IF;
	    --##CHK AC_CODE_DTL
	    IF MST_CRSR.AC_CODE_DTL IS NOT NULL THEN
		IF NVL(MST_CRSR.AC_DTL_TYP,0) = 3 THEN
		    BEGIN
			SELECT 1 INTO V_CNT
				 FROM CUSTOMER,ACCOUNT
				WHERE ACCOUNT.A_CODE =CUSTOMER.C_A_CODE
				  AND NVL (INACTIVE, 0)  = 0
				  AND CUSTOMER.C_A_CODE  = MST_CRSR.A_CODE
				  AND CUSTOMER.C_CODE	 = MST_CRSR.AC_CODE_DTL
				  AND ACCOUNT.AC_DTL_TYP = MST_CRSR.AC_DTL_TYP
				  AND ACCOUNT.AC_DTL_TYP = 3
				  AND ROWNUM <=1;

		    EXCEPTION
			WHEN OTHERS THEN
			    V_CNT := 0;
		    END;
		    IF V_CNT = 0 THEN
			RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 3,P_MSG_TXT => '');
		    END IF;
		END IF;
	    ELSIF MST_CRSR.AC_CODE_DTL IS NULL AND NVL(MST_CRSR.AC_DTL_TYP,0)<>0 THEN
		   RETURN GET_ERR_FNC(P_LBL_NO => NULL,P_MSG_NO => 4559,P_MSG_TXT => '');
	    END IF;

	    --##INSERT DATA
	    BEGIN
		INSERT INTO POS_GNR_EXPNS( DOC_NO
					  ,DOC_SRL
					  ,DOC_DATE
					  ,DOC_TIME
					  ,REF_NO
					  ,CUR_CODE
					  ,EX_RATE
					  ,DOC_AMT
					  ,DOC_DSC
					  ,CASH_NO
					  ,MACHINE_NO
					  ,EXTRNL_PST
					  ,A_CODE
					  ,AC_CODE_DTL
					  ,AC_DTL_TYP
					  ,MOBILE_NO
					  ,CC_CODE
					  ,PJ_NO
					  ,ACTV_NO
					  ,PST_FLG
					  ,AD_U_ID
					  ,AD_DATE
					  ,AD_TRMNL_NM
					  ,DOC_NO_REF
					  ,DOC_SRL_REF
					  ,DOC_TYP_REF
					  ,SHFT_SRL
					  ,BRN_NO
					  ,BRN_YEAR
					  ,BRN_USR
					  ,CMP_NO)
		       VALUES (G_DOC_NO
			      ,G_DOC_SRL
			      ,L_DOC_DATE
			      ,MST_CRSR.DOC_TIME
			      ,MST_CRSR.REF_NO
			      ,MST_CRSR.CUR_CODE
			      ,MST_CRSR.EX_RATE
			      ,NVL(MST_CRSR.DOC_AMT,0)
			      ,MST_CRSR.DOC_DSC
			      ,G_CASH_NO
			      ,G_TRMNL_NO
			      ,0
			      ,MST_CRSR.A_CODE
			      ,MST_CRSR.AC_CODE_DTL
			      ,MST_CRSR.AC_DTL_TYP
			      ,MST_CRSR.MOBILE_NO
			      ,MST_CRSR.CC_CODE
			      ,MST_CRSR.PJ_NO
			      ,MST_CRSR.ACTV_NO
			      ,0
			      ,G_USR_NO
			      ,G_AD_DATE
			      ,MST_CRSR.AD_TRMNL_NM
			      ,MST_CRSR.DOC_NO_REF
			      ,MST_CRSR.DOC_SRL_REF
			      ,MST_CRSR.DOC_TYP_REF
			      ,MST_CRSR.SHFT_SRL
			      ,G_BRN_NO
			      ,G_BRN_YEAR
			      ,G_BRN_USR
			      ,G_CMP_NO);

			      L_ROW_INSRTD := TRUE;
	    EXCEPTION
		WHEN OTHERS THEN
		    ROLLBACK;
		    RETURN '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"ERROR WHEN INSERT INTO POS_GNR_EXPNS ' || GET_SQLERRM || '","_ErrNo":-9 } }';
	    END;


	END LOOP;

	IF G_DOC_NO IS NOT NULL AND G_DOC_SRL IS NOT NULL THEN

	    IF L_ROW_INSRTD THEN
		L_ERR_MSG := PST_COMMIT_PRC;

		IF L_ERR_MSG IS NOT NULL THEN
		    L_JSON_RSLT := '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"' || REPLACE(L_ERR_MSG,'"','') || '","_ErrNo":-10 } }';
		END IF;
	    ELSE
		L_JSON_RSLT := '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"NO DATA INSERTED","_ErrNo":-11 } }';
	    END IF;


	ELSE
	    L_JSON_RSLT := '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"NO DATA INSERTED","_ErrNo":-12 } }';
	END IF;

	IF L_JSON_RSLT IS NULL THEN
	    COMMIT;
	    L_JSON_RSLT := '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"SUCCESSFUL","_ErrNo":0 } }';
	ELSE
	    ROLLBACK;
	END IF;

	RETURN L_JSON_RSLT;

    EXCEPTION
	WHEN OTHERS THEN
	    ROLLBACK;
	    RETURN '{"_Result": { "_Doc_No":"' || G_DOC_NO || '","_Doc_Srl":"' || G_DOC_SRL || '","_ErrMsg":"ERROR IN INSRT_EXPNS_CNTS ' || GET_SQLERRM || '","_ErrNo":-13 } }';
    END INSRT_EXPNS;
--#----------------------------------------------------------------------------------------------------------#--
    FUNCTION GET_CSTMR_DATA(P_DOC_SRL_REF IN SALES_ORDER.ORDER_SER%TYPE) RETURN CLOB
    IS
    BEGIN

	RETURN POS_RCPTS_EXPNS_API_PKG.GET_XML_QRY(P_QRY_STR => 'SELECT MOBILE_NO,C_NAME
						       FROM SALES_ORDER
						      WHERE ORDER_SER = '||P_DOC_SRL_REF||' AND ROWNUM <= 1',
				       P_ROW_TAG_NM => 'C_NAME');
    EXCEPTION
	WHEN OTHERS
	THEN
	    RETURN '{"_Result": {"_ErrMsg":"ERROR IN GET_CSTMR_DATA ' || GET_SQLERRM || '","_ErrNo":-14 } }';
    END GET_CSTMR_DATA;
--#----------------------------------------------------------------------------------------------------------#--
    FUNCTION GET_ACCNT_LST (P_LANG_NO	   IN IAS_LABELS.LANG_NO%TYPE,
			    P_USR_NO	 IN USER_R.U_ID%TYPE,
			    P_AC_DTL_TYP IN NUMBER DEFAULT NULL,
			    P_WHR	 IN VARCHAR2 DEFAULT NULL)   --##0 GNRL 3-CUSTOMER  4-Dept 5-Credit 7-Emp
	RETURN CLOB IS
    BEGIN
	IF P_AC_DTL_TYP IS NOT NULL THEN
	    V_WHR := ' AND Nvl(M.Ac_Dtl_Typ,0)='||P_AC_DTL_TYP;
	END IF;
	IF P_WHR IS NOT NULL THEN
	    V_WHR:=V_WHR||' '||P_WHR;
	END IF;
       RETURN POS_RCPTS_EXPNS_API_PKG.GET_XML_QRY(P_QRY_STR => 'Select	M.A_Code,M.A_Name,M.A_Name_Eng,D.A_CY
	    From Account M,Account_Curr D
	     Where M.A_code = D.A_code
	       and nvl(D.Inactive,0)=0
		'||V_WHR||'
	       And Exists(Select Account_Type
		  From Account_Types
		 Where Nvl(Affected_By_Trans, 0) = 1 And Account_Type = M.A_S_M)
	 And Exists(
	    Select 1
	      From Priv_Acc
	     Where U_Id = '||P_USR_NO||'
	       And A_Code = M.A_Code
	       And Add_Flag = 1
	       And Rownum <= 1)',
	   P_ROW_TAG_NM => 'ACODE');
    EXCEPTION
	WHEN OTHERS
	THEN
	    RETURN '{"_Result": {"_ErrMsg":"ERROR IN GET_AC_CODE_LST ' || GET_SQLERRM || '","_ErrNo":-15 } }';
    END GET_ACCNT_LST;
--#----------------------------------------------------------------------------------------------------------#--
    FUNCTION GET_ACCNT_DTL_LST (P_LANG_NO    IN IAS_LABELS.LANG_NO%TYPE,
				P_USR_NO     IN USER_R.U_ID%TYPE,
				P_AC_DTL_TYP IN POS_GNR_RCPTS.AC_DTL_TYP%TYPE,
				P_AC_CODE    IN POS_GNR_RCPTS.A_CODE%TYPE DEFAULT NULL,
				P_WHR	     IN VARCHAR2 DEFAULT NULL  )
	RETURN CLOB
    IS
       L_QRY_STR  CLOB;
    BEGIN

	IF P_WHR IS NOT NULL THEN
	    V_WHR:=P_WHR;
	END IF;
	IF P_AC_DTL_TYP = 3 THEN
	IF P_AC_CODE IS NOT NULL THEN
	    V_WHR := V_WHR||'  AND M.C_A_CODE = '''||P_AC_CODE||''' ';
	END IF;
	    L_QRY_STR := 'SELECT M.C_CODE AC_CODE_DTL ,M.C_A_NAME AC_CODE_DTL_L_NM, M.C_E_NAME AC_CODE_DTL_F_NM,C_A_CODE AC_CODE,D.A_CY
			  FROM CUSTOMER M,CUSTOMER_CURR D
			 WHERE M.C_CODE=D.C_CODE AND NVL(D.INACTIVE,0)=0
			   '||V_WHR||'
			   AND EXISTS (SELECT 1
					 FROM PRIV_ACC
					WHERE U_ID = ' || P_USR_NO || '
					  AND A_CODE = M.C_A_CODE
					  AND NVL (ADD_FLAG, 0) = 1
					  AND ROWNUM <= 1)';

	ELSIF P_AC_DTL_TYP IN (5,6) THEN
	IF P_AC_CODE IS NOT NULL THEN
	    V_WHR := V_WHR||'  AND M.AC_CODE = '''||P_AC_CODE||''' ';
	END IF;
	     L_QRY_STR := ' SELECT AC_CODE_DTL,AC_CODE_DTL_L_NM, AC_CODE_DTL_F_NM,AC_CODE
			   FROM GlS_ACCNT_DTL
			    WHERE AC_DTL_TYP='||P_AC_DTL_TYP ||' '||V_WHR;

	ELSIF P_AC_DTL_TYP = 7 THEN
	    L_QRY_STR := 'SELECT M.EMP_NO AC_CODE_DTL,M.EMP_L_NM AC_CODE_DTL_L_NM, M.EMP_F_NM AC_CODE_DTL_F_NM
			  FROM S_EMP M
			 WHERE NVL(INACTIVE, 0) = 0
			   AND EXISTS
				    (SELECT 1
				       FROM DUAL
				      WHERE YS_GEN_PKG.GET_FLD_VALUE(''IAS_PARA_GEN'', ''EMP_PRV_TYP'') = 0
				     UNION
				     SELECT 1
				       FROM S_EMP_PRV
				      WHERE U_ID = '||P_USR_NO||'
					AND EMPNO_HRCHYNO = DECODE(EMP_PRV_TYP,  1, M.EMP_NO,  2, M.HRCHY_NO)
					AND NVL(ADD_FLAG,0) = 1
					AND ROWNUM <= 1)
			   AND EXISTS
				   (SELECT 1
				      FROM S_BRN_USR_PRIV
				     WHERE BRN_NO = M.BRN_NO
				       AND VIEW_FLAG = 1
				       AND U_ID = '||P_USR_NO||'
				       AND ROWNUM <= 1)';
	END IF;

	RETURN POS_RCPTS_EXPNS_API_PKG.GET_XML_QRY(P_QRY_STR => L_QRY_STR, P_ROW_TAG_NM => 'AC_CODE_DTL');

    EXCEPTION WHEN OTHERS  THEN
	    RETURN '{"_Result": {"_ErrMsg":"ERROR IN GET_ACCNT_DTL_LST ' || GET_SQLERRM || '","_ErrNo":-16 } }';
    END GET_ACCNT_DTL_LST;
--#----------------------------------------------------------------------------------------------------------#--
    FUNCTION GET_RCPTS(P_DOC_SRL IN POS_GNR_RCPTS.DOC_SRL%TYPE DEFAULT NULL) RETURN CLOB
    IS
    V_WHR   VARCHAR2(100) :=NULL;
    BEGIN
	IF P_DOC_SRL IS NOT NULL THEN
	    V_WHR := ' AND M.DOC_SRL = '||P_DOC_SRL;
	END IF;
	RETURN POS_RCPTS_EXPNS_API_PKG.GET_XML_QRY(P_QRY_STR => 'M.DOC_SRL,M.DOC_NO,M.DOC_DATE,M.DOC_DSC,M.CUR_CODE,M.EX_RATE,DOC_AMT,M.A_CODE,M.DOC_NO_REF,R.MOBILE_NO,R.C_NAME
						       FROM POS_GNR_RCPTS M,SALES_ORDER R
						      WHERE M.DOC_SRL_REF = R.ORDER_SER(+) '||V_WHR||'
							AND M.PRCSS_FLG   = 0
							AND M.PST_FLG	= 0
						   ORDER BY M.DOC_DATE,M.DOC_NO',
				       P_ROW_TAG_NM => 'RCPTS');

    EXCEPTION
	WHEN OTHERS
	THEN
	    RETURN '{"_Result": {"_ErrMsg":"ERROR IN GET_RCPTS ' || GET_SQLERRM || '","_ErrNo":-18 } }';
    END GET_RCPTS;
--#----------------------------------------------------------------------------------------------------------#--
FUNCTION GET_EXPNS(P_DOC_SRL IN POS_GNR_EXPNS.DOC_SRL%TYPE DEFAULT NULL) RETURN CLOB
    IS
    V_WHR   VARCHAR2(100) :=NULL;
    BEGIN
	IF P_DOC_SRL IS NOT NULL THEN
	    V_WHR := ' AND DOC_SRL = '||P_DOC_SRL;
	END IF;
	RETURN POS_RCPTS_EXPNS_API_PKG.GET_XML_QRY(P_QRY_STR => 'SELECT DOC_SRL,DOC_NO,DOC_DATE,DOC_DSC,CUR_CODE,EX_RATE,DOC_AMT,A_CODE,MOBILE_NO,MACHINE_NO
						       FROM POS_GNR_EXPNS
						      WHERE PST_FLG=0
							 '||V_WHR||'
						   ORDER BY DOC_DATE DESC,DOC_NO',
				       P_ROW_TAG_NM => 'EXPNS');

    EXCEPTION
	WHEN OTHERS
	THEN
	    RETURN '{"_Result": {"_ErrMsg":"ERROR IN GET_EXPNS ' || GET_SQLERRM || '","_ErrNo":-18 } }';
    END GET_EXPNS;
--#----------------------------------------------------------------------------------------------------------#--
 FUNCTION GET_XML_QRY (P_QRY_STR IN VARCHAR2,P_ROW_TAG_NM VARCHAR2)
	RETURN CLOB
    IS
	QRY_RSLT   CLOB;
	QRY_CTX    DBMS_XMLGEN.CTXHANDLE;
    BEGIN
	QRY_CTX := DBMS_XMLGEN.NEWCONTEXT (P_QRY_STR);

	DBMS_XMLGEN.SETROWTAG (QRY_CTX,P_ROW_TAG_NM);
	DBMS_XMLGEN.SETNULLHANDLING (QRY_CTX, DBMS_XMLGEN.EMPTY_TAG);
	QRY_RSLT := DBMS_XMLGEN.GETXML (QRY_CTX);

	RETURN QRY_RSLT;
    END GET_XML_QRY;
    --#----------------------------------------------------------------------------------------------------------#--
    FUNCTION GET_CSTMRS(P_LANG_NO    IN IAS_LABELS.LANG_NO%TYPE,
			P_CUR_CODE   IN POS_GNR_RCPTS.CUR_CODE%TYPE,
			P_USR_NO     IN USER_R.U_ID%TYPE) RETURN CLOB IS
    BEGIN

	RETURN POS_RCPTS_EXPNS_API_PKG.GET_XML_QRY(P_QRY_STR => 'SELECT CUSTOMER.C_CODE,
							    DECODE('||P_LANG_NO||',1, NVL (C_A_NAME, C_E_NAME),
								    NVL (C_E_NAME, C_A_NAME)) C_NAME,
							    DECODE('||P_LANG_NO||',1, NVL (C_GROUP_A_NAME, C_GROUP_E_NAME),
								    NVL (C_GROUP_E_NAME, C_GROUP_A_NAME)) GROUP_NAME,
							    CUSTOMER.C_A_CODE A_CODE
						       FROM CUSTOMER,CUSTOMER_GROUP
						      WHERE CUSTOMER.C_GROUP_CODE = CUSTOMER_GROUP.C_GROUP_CODE(+)
							AND EXISTS(SELECT 1 FROM IAS_PRIV_CUSTOMER R WHERE R.U_ID ='||P_USR_NO||' AND R.C_CODE = CUSTOMER.C_CODE AND R.A_CY = '''||P_CUR_CODE||''')',
				       P_ROW_TAG_NM => 'CSTMRS');

    EXCEPTION
	WHEN OTHERS
	THEN
	    RETURN '{"_Result": {"_ErrMsg":"ERROR IN GET_CSTMRS ' || GET_SQLERRM || '","_ErrNo":-19 } }';
    END GET_CSTMRS;
BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_DATE_FORMAT=''DD/MM/YYYY''';

END POS_RCPTS_EXPNS_API_PKG;
/
