-- =============================================
-- PACKAGE SPEC: POS_OTHR_CHRG_PKG  (status: INVALID)
-- =============================================
CREATE OR REPLACE
PACKAGE POS_OTHR_CHRG_PKG
IS
    G_BRN_NO		      IAS_POS_BILL_MST.BRN_NO%TYPE;
    G_BILL_SRL		      IAS_POS_BILL_MST.BILL_SRL%TYPE;
    G_BILL_NO		      IAS_POS_BILL_MST.BILL_NO%TYPE;
    G_BILL_DATE 	      IAS_POS_BILL_MST.BILL_DATE%TYPE;
    G_BILL_TYPE 	      IAS_POS_BILL_MST.BILL_TYPE%TYPE;
    G_CLC_TYP_NO_TAX	      IAS_POS_BILL_MST.CLC_TYP_NO_TAX%TYPE;
    G_BILL_RATE 	      IAS_POS_BILL_MST.BILL_RATE%TYPE;
    G_BILL_AMT		      IAS_POS_BILL_MST.BILL_AMT%TYPE;
    G_SI_TYPE		      IAS_POS_BILL_MST.SI_TYPE%TYPE;
    G_A_CY		      IAS_POS_BILL_MST.A_CY%TYPE;
    G_MACHINE_NO	      IAS_POS_BILL_MST.MACHINE_NO%TYPE;
    G_AD_U_ID		      IAS_POS_BILL_MST.AD_U_ID%TYPE;
    G_AD_TRMNL_NM	      IAS_POS_BILL_MST.AD_TRMNL_NM%TYPE;
    G_AD_DATE		      IAS_POS_BILL_MST.AD_DATE%TYPE := TO_DATE (YS_GEN_PKG.GET_CURDATE, 'DD/MM/YYYY');
    G_USE_PRICE_INCLUDE_VAT   IAS_PARA_GEN.USE_PRICE_INCLUDE_VAT%TYPE;
    G_ACTIVE_VAT_DATE	      IAS_PARA_GEN.ACTIVE_VAT_DATE%TYPE;
    G_USE_VAT		      IAS_PARA_GEN.USE_VAT%TYPE;
    G_CALC_VAT_AMT_TYPE       IAS_PARA_AR.CALC_VAT_AMT_TYPE%TYPE;
    G_NO_OF_DECIMAL	      NUMBER := 2;
    G_LNG_NO		      IAS_LABELS.LANG_NO%TYPE DEFAULT 1;


    FUNCTION INSRT_OTHR_CHRG_MVMNT (
	P_DOC_TYP	  IN NUMBER ,
	P_BILL_NO	  IN IAS_POS_BILL_MST.BILL_NO%TYPE  ,
	P_BILL_SRL	  IN IAS_POS_BILL_MST.BILL_SRL%TYPE ,
	P_XML_INPT	  IN CLOB DEFAULT NULL,
	P_LNG_NO	  IN IAS_LABELS.LANG_NO%TYPE DEFAULT 1)
	RETURN VARCHAR2;

    FUNCTION LOAD_PRMTRS
	RETURN VARCHAR2;
END POS_OTHR_CHRG_PKG;
/

-- ---------------------------------------------
-- PACKAGE BODY: POS_OTHR_CHRG_PKG  (status: INVALID)
-- ---------------------------------------------
CREATE OR REPLACE
PACKAGE BODY POS_OTHR_CHRG_PKG
IS
    FUNCTION GET_SQLERRM
	RETURN VARCHAR2
    IS
	L_SQLERRM VARCHAR2(2000) := SQLERRM;
    BEGIN
	RETURN REPLACE(L_SQLERRM,'"','');
    END GET_SQLERRM;
--#----------------------------------------------------------------------------------------------------------#--
    FUNCTION LOAD_PRMTRS RETURN VARCHAR2
    IS
    BEGIN
	BEGIN
	    SELECT NVL(CLC_TYP_NO_TAX, 0)
	      INTO G_CLC_TYP_NO_TAX
	      FROM IAS_POS_MACHINE
	     WHERE MACHINE_NO = G_MACHINE_NO AND ROWNUM <= 1;
	EXCEPTION
	    WHEN OTHERS THEN
		RETURN 'EXCEPTION WHEN GET CLC_TYP_NO_TAX IN MACHINE_NO '||G_MACHINE_NO ||CHR(13)||GET_SQLERRM;
	END;

	BEGIN
	    SELECT NVL(USE_PRICE_INCLUDE_VAT, 0),
		   ACTIVE_VAT_DATE,
		   NVL(IAS_PARA_AR.CALC_VAT_AMT_TYPE, 0),
		   NVL(USE_VAT, 0),
		   NVL(IAS_PARA_AR.NO_OF_DECIMAL_AR, 2)
	      INTO G_USE_PRICE_INCLUDE_VAT,
		   G_ACTIVE_VAT_DATE,
		   G_CALC_VAT_AMT_TYPE,
		   G_USE_VAT,
		   G_NO_OF_DECIMAL
	      FROM IAS_PARA_GEN, IAS_PARA_AR
	      WHERE ROWNUM<=1;
	EXCEPTION
	    WHEN OTHERS THEN
		RETURN 'ERROR WHEN GET PARAMETERS FROM IAS_PARA_AR IAS_PARA_GEN ' || GET_SQLERRM;
	END ;

	RETURN NULL;
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN 'ERROR IN GET PARAMETERS';
    END LOAD_PRMTRS;
--#----------------------------------------------------------------------------------------------------------#--
FUNCTION INSRT_OTHR_CHRG_MVMNT( P_DOC_TYP	  IN NUMBER ,
				P_BILL_NO	  IN IAS_POS_BILL_MST.BILL_NO%TYPE  ,
				P_BILL_SRL	  IN IAS_POS_BILL_MST.BILL_SRL%TYPE ,
				P_XML_INPT	  IN CLOB DEFAULT NULL,
				P_LNG_NO	  IN IAS_LABELS.LANG_NO%TYPE DEFAULT 1)
				RETURN VARCHAR2
    IS
	L_XML_INPT	   XMLTYPE;
	L_SC_AMT	   NUMBER;
	L_SC_NM 	   POS_OTHR_CHRG_MVMNT.SC_NM%TYPE;
	L_VAT_AMT	   NUMBER;
	L_VAT_PRCNT	   NUMBER;
	L_OTHR_AMT	   IAS_POS_BILL_MST.OTHR_AMT%TYPE;
	L_VAT_AMT_OTHR	   IAS_POS_BILL_MST.VAT_AMT_OTHR%TYPE;
	L_BILL_CHRG_TBL_NM VARCHAR(60) := 'POS_OTHR_CHRG_MVMNT';
	L_ERR_MSG	   VARCHAR2(4000);
	V_RCRD_NO	   NUMBER := 0;
	V_CNT		   NUMBER := 0;
	L_AMT_TYPE	   SALES_CHARGES.AMT_TYPE %TYPE;
	L_SC_TYPE	   SALES_CHARGES.SC_TYPE%TYPE;
	V_XML_TAG	   VARCHAR(50);
	V_TBL_MST_NM	   VARCHAR(50);
	V_TBL_DTL_NM	   VARCHAR(50);
	V_P_FLD_DOC_SER    VARCHAR(50);
	V_FLD_DOC_AMT	   VARCHAR(50);
	V_FLD_DOC_SER_INPT VARCHAR(50);
	V_TBL_INPT_NM	   VARCHAR(50);
    BEGIN
	G_BILL_SRL :=P_BILL_SRL;
	G_BILL_NO  :=P_BILL_NO ;
	G_LNG_NO   :=P_LNG_NO;
     If P_DOC_TYP=4 Then
	V_XML_TAG:='IAS_POS_BILL';
	BEGIN
	    SELECT BRN_NO,
		   BILL_TYPE,
		   BILL_AMT,
		   A_CY,
		   BILL_RATE,
		   MACHINE_NO,
		   AD_U_ID,
		   AD_TRMNL_NM,
		   AD_DATE,
		   BILL_DATE,
		   SI_TYPE
	      INTO G_BRN_NO,
		   G_BILL_TYPE,
		   G_BILL_AMT,
		   G_A_CY,
		   G_BILL_RATE,
		   G_MACHINE_NO,
		   G_AD_U_ID,
		   G_AD_TRMNL_NM,
		   G_AD_DATE,
		   G_BILL_DATE,
		   G_SI_TYPE
	      FROM IAS_POS_BILL_MST
	     WHERE BILL_NO = G_BILL_NO AND BILL_SRL = G_BILL_SRL AND ROWNUM <= 1;
	EXCEPTION
	    WHEN OTHERS THEN
		RETURN 'EXCEPTION WHEN GET BILL DATA BILL_NO ='||P_BILL_NO||CHR(13)||GET_SQLERRM;
	END;
     ElsIf P_DOC_TYP=149 Then
       V_XML_TAG:='SAL_ORDR';
	BEGIN
	    SELECT BRN_NO,
		   PYMNT_TYPE,
		   ORDER_AMT,
		   ORDER_CUR,
		   CUR_RATE,
		   MACHINE_NO,
		   AD_U_ID,
		   AD_TRMNL_NM,
		   AD_DATE,
		   ORDER_DATE,
		   SI_TYPE
	      INTO G_BRN_NO,
		   G_BILL_TYPE,
		   G_BILL_AMT,
		   G_A_CY,
		   G_BILL_RATE,
		   G_MACHINE_NO,
		   G_AD_U_ID,
		   G_AD_TRMNL_NM,
		   G_AD_DATE,
		   G_BILL_DATE,
		   G_SI_TYPE
	      FROM Sales_Order
	     WHERE ORDER_NO = G_BILL_NO AND ORDER_SER = G_BILL_SRL AND ROWNUM <= 1;
	EXCEPTION
	    WHEN OTHERS THEN
		RETURN 'EXCEPTION WHEN GET Sales_Order DATA ORDER_SER ='||P_BILL_NO||CHR(13)||GET_SQLERRM;
	END;
     Else
	RAISE_APPLICATION_ERROR(-20201,'ERR WHEN INSRT_OTHR_CHRG_MVMNT_PRC P_DOC_TYP IS WRONG OR NULL ');
     End If;
	L_ERR_MSG := LOAD_PRMTRS;

	IF L_ERR_MSG IS NOT NULL THEN
	    RETURN L_ERR_MSG;
	END IF;
	IF P_DOC_TYP=149 THEN
	  BEGIN
	    DELETE FROM POS_RQ_OTHR_CHRG_MVMNT WHERE DOC_TYPE=P_DOC_TYP AND DOC_SRL=P_BILL_SRL;
	  EXCEPTION WHEN OTHERS THEN
	      NULL;
	   END;
	ELSE
	 EXECUTE IMMEDIATE 'DELETE FROM '||L_BILL_CHRG_TBL_NM||' WHERE DOC_TYPE = '||P_DOC_TYP||' AND BILL_NO = '||P_BILL_NO||' AND BILL_SRL ='||P_BILL_SRL;
	End If;
	IF P_XML_INPT IS NOT NULL THEN
	    L_XML_INPT	:= XMLTYPE.CREATEXML(P_XML_INPT);
	    FOR OTHR_CHRG_C IN (SELECT	 EXTRACTVALUE (VALUE (XMLMSTDMY), '*/SC_NO	') AS  SC_NO
				      ,EXTRACTVALUE (VALUE (XMLMSTDMY), '*/SC_PRCNT   ') AS  SC_PRCNT
				      ,EXTRACTVALUE (VALUE (XMLMSTDMY), '*/SC_AMT     ') AS  SC_AMT
				      ,EXTRACTVALUE (VALUE (XMLMSTDMY), '*/SC_A_CY    ') AS  SC_A_CY
				      ,EXTRACTVALUE (VALUE (XMLMSTDMY), '*/SC_AC_RATE ') AS  SC_AC_RATE
				      ,EXTRACTVALUE (VALUE (XMLMSTDMY), '*/A_CY       ') AS  A_CY
				      ,EXTRACTVALUE (VALUE (XMLMSTDMY), '*/AC_RATE  ') AS  AC_RATE
				      ,EXTRACTVALUE (VALUE (XMLMSTDMY), '*/RCRD_NO    ') AS  RCRD_NO
				      ,EXTRACTVALUE (VALUE (XMLMSTDMY), '*/VAT_AMT    ') AS  VAT_AMT
				      ,EXTRACTVALUE (VALUE (XMLMSTDMY), '*/VAT_PRCNT  ') AS  VAT_PRCNT
			  FROM TABLE  (XMLSEQUENCE (EXTRACT (L_XML_INPT, '/'||V_XML_TAG||'/POS_OTHR_CHRG_MVMNT'))) XMLMSTDMY)
	    LOOP
		DECLARE
		    PROCEDURE INSRT_OTHR_CHRG_MVMNT_PRC
		    IS
		    BEGIN

			INSERT INTO POS_OTHR_CHRG_MVMNT(DOC_TYPE,
						  SC_NO,
						  SC_NM,
						  SC_PRCNT,
						  SC_AMT,
						  A_CY,
						  AC_RATE,
						  RCRD_NO,
						  BILL_NO,
						  BILL_SRL,
						  SC_A_CY,
						  SC_AC_RATE,
						  VAT_AMT,
						  VAT_PRCNT,
						  AD_U_ID,
						  AD_DATE,
						  AD_TRMNL_NM)
					   VALUES(P_DOC_TYP,
						  OTHR_CHRG_C.SC_NO,
						  L_SC_NM,
						  OTHR_CHRG_C.SC_PRCNT,
						  L_SC_AMT,	    --SC_AMT,
						  G_A_CY,
						  G_BILL_RATE,	    --AC_RATE,
						  V_RCRD_NO,
						  G_BILL_NO,
						  G_BILL_SRL,
						  OTHR_CHRG_C.SC_A_CY,	 --SC_A_CY,
						  OTHR_CHRG_C.SC_AC_RATE,--SC_AC_RATE,
						  OTHR_CHRG_C.VAT_AMT,
						  OTHR_CHRG_C.VAT_PRCNT,
						  G_AD_U_ID,
						  G_AD_DATE,
						  G_AD_TRMNL_NM);
		    EXCEPTION
			WHEN OTHERS THEN
			    RAISE_APPLICATION_ERROR(-20201,'EXCEPTION IN INSRT_BILL_SRVCS WHEN INSRT_OTHR_CHRG_MVMNT_PRC '||GET_SQLERRM);
		    END INSRT_OTHR_CHRG_MVMNT_PRC;
		    PROCEDURE INSRT_RQ_OTHR_CHRG_MVMNT_PRC
		    IS
		    BEGIN
		     INSERT INTO POS_RQ_OTHR_CHRG_MVMNT(DOC_TYPE,
						  SC_NO,
						  SC_NM,
						  SC_PRCNT,
						  SC_AMT,
						  A_CY,
						  AC_RATE,
						  RCRD_NO,
						  DOC_NO,
						  DOC_SRL,
						  SC_A_CY,
						  SC_AC_RATE,
						  VAT_AMT,
						  VAT_PRCNT,
						  AD_U_ID,
						  AD_DATE,
						  AD_TRMNL_NM)
					   VALUES(P_DOC_TYP,
						  OTHR_CHRG_C.SC_NO,
						  L_SC_NM,
						  OTHR_CHRG_C.SC_PRCNT,
						  L_SC_AMT,	    --SC_AMT,
						  G_A_CY,
						  G_BILL_RATE,	    --AC_RATE,
						  V_RCRD_NO,
						  G_BILL_NO,
						  G_BILL_SRL,
						  OTHR_CHRG_C.SC_A_CY,	 --SC_A_CY,
						  OTHR_CHRG_C.SC_AC_RATE,--SC_AC_RATE,
						  OTHR_CHRG_C.VAT_AMT,
						  OTHR_CHRG_C.VAT_PRCNT,
						  G_AD_U_ID,
						  G_AD_DATE,
						  G_AD_TRMNL_NM);
		    EXCEPTION
			WHEN OTHERS THEN
			    RAISE_APPLICATION_ERROR(-20202,'EXCEPTION  WHEN POS_RQ_OTHR_CHRG_MVMNT  '||GET_SQLERRM);
		    END INSRT_RQ_OTHR_CHRG_MVMNT_PRC;


		BEGIN
		    IF OTHR_CHRG_C.SC_NO IS NULL THEN
			RETURN	IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 1318)||CHR(32)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 21086)||CHR(32)||IAS_GEN_PKG.GET_MSG(P_LNG_NO => G_LNG_NO, P_MSG_NO => 125)
				||CHR(10)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 349)||' = '||G_BILL_NO
				||CHR(10)||GET_SQLERRM;
		    END IF;

		    IF OTHR_CHRG_C.SC_PRCNT IS NULL THEN
			RETURN	IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 920)||CHR(32)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 2297)||CHR(32)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 21086)||CHR(32)||IAS_GEN_PKG.GET_MSG(P_LNG_NO => G_LNG_NO, P_MSG_NO => 125)
				||CHR(10)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 1318)||' = '||OTHR_CHRG_C.SC_NO
				||CHR(10)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 349) ||' = '||G_BILL_NO
				||CHR(10)||GET_SQLERRM;
		    END IF;

		    IF	OTHR_CHRG_C.A_CY IS NULL THEN
			RETURN	IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 9)||CHR(32)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 21086)||CHR(32)||IAS_GEN_PKG.GET_MSG(P_LNG_NO => G_LNG_NO, P_MSG_NO => 125)
				||CHR(10)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 1318)||' = '||OTHR_CHRG_C.SC_NO
				||CHR(10)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 349) ||' = '||G_BILL_NO
				||CHR(10)||GET_SQLERRM;
		    ELSE
			BEGIN
			    SELECT 1
			      INTO V_CNT
			      FROM EX_RATE
			     WHERE CUR_CODE = OTHR_CHRG_C.A_CY AND ROWNUM <=1;
			EXCEPTION
			    WHEN OTHERS THEN
				V_CNT := 0;
			END;

			IF NVL (V_CNT, 0) = 0 THEN
			    RETURN  IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 9)||CHR(32)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 21086)||' = '||OTHR_CHRG_C.A_CY||CHR(32)||IAS_GEN_PKG.GET_MSG(P_LNG_NO => G_LNG_NO, P_MSG_NO => 125)
				    ||CHR(10)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 1318)||' = '||OTHR_CHRG_C.SC_NO
				    ||CHR(10)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 349) ||' = '||G_BILL_NO
				    ||CHR(10)||GET_SQLERRM;
			END IF;

			IF OTHR_CHRG_C.AC_RATE IS NULL THEN
			    OTHR_CHRG_C.AC_RATE := IAS_USR_PKG.GET_CUR_RATE(P_ACY=>OTHR_CHRG_C.A_CY,P_USR_NO => G_AD_U_ID);
			END IF;
		    END IF;

		    IF NVL(OTHR_CHRG_C.SC_AMT,0) <= 0 THEN
			RETURN	IAS_GEN_PKG.GET_MSG(P_LNG_NO => G_LNG_NO, P_MSG_NO => 524)
				||CHR(10)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 2760) ||' = '||OTHR_CHRG_C.SC_AMT
				||CHR(10)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 1318)||' = '||OTHR_CHRG_C.SC_NO
				||CHR(10)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 349) ||' = '||G_BILL_NO
				||CHR(10)||GET_SQLERRM;
		    END IF;

		    L_SC_AMT := OTHR_CHRG_C.SC_AMT;

		    IF OTHR_CHRG_C.SC_A_CY IS NOT NULL AND OTHR_CHRG_C.SC_AC_RATE IS NULL THEN
			OTHR_CHRG_C.SC_AC_RATE := IAS_USR_PKG.GET_CUR_RATE(P_ACY=>OTHR_CHRG_C.SC_A_CY,P_USR_NO => G_AD_U_ID);
		    END IF;

		    V_RCRD_NO := OTHR_CHRG_C.RCRD_NO;
		    IF V_RCRD_NO IS NULL THEN
			BEGIN
			    SELECT NVL(MAX(RCRD_NO),0)+1
				   INTO V_RCRD_NO
				   FROM POS_OTHR_CHRG_MVMNT
				   WHERE DOC_TYPE=P_DOC_TYP AND BILL_NO = G_BILL_NO AND BILL_SRL =G_BILL_SRL;
			EXCEPTION
			    WHEN OTHERS THEN
				V_RCRD_NO := 1;
			END;
		    END IF;

		    BEGIN
			SELECT 1,SC_NAME,AMT_TYPE,SC_TYPE
			  INTO V_CNT,L_SC_NM,L_AMT_TYPE,L_SC_TYPE
			  FROM SALES_CHARGES
			 WHERE --NVL(FILL_AUTO, 0) = 1
			       NVL(INACTIVE, 0) = 0
			   AND NVL(INV_ITEM, 0) = 0
			   AND (NVL(USE_IN_POS_FLG,0) = 1 Or NVL(Use_Sc_In_Sho_Sys_Flg,0)=1 )
			   AND NVL(SC_TYPE,0) IN(1,2)
			   AND AMT_TYPE IN (0,1)
			   AND DECODE(BILL_DOC_TYPE,NULL,0,BILL_DOC_TYPE) = DECODE(BILL_DOC_TYPE,NULL,0,G_BILL_TYPE)
			   AND SC_NO = OTHR_CHRG_C.SC_NO
			   And nvl(Sc_Add_Frc_Invoice,0)<>1
			   AND ROWNUM <=1;
		    EXCEPTION
			WHEN OTHERS THEN
			    V_CNT := 0;
		    END;
		    IF V_CNT = 0 THEN
			RETURN	IAS_GEN_PKG.GET_MSG(P_LNG_NO => G_LNG_NO, P_MSG_NO => 5707)||CHR(32)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 876)||CHR(32)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 2297)
				||CHR(10)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 1318)||' = '||OTHR_CHRG_C.SC_NO
				||CHR(10)||IAS_GEN_PKG.GET_PROMPT(P_LNG_NO => G_LNG_NO, P_LBL_NO => 349) ||' = '||G_BILL_NO
				||CHR(10)||GET_SQLERRM;
		    END IF;

		    IF L_SC_TYPE = 2 THEN
			L_SC_AMT := L_SC_AMT * -1;	
		    END IF;
		    If P_DOC_TYP=4 Then
				    BEGIN
					INSRT_OTHR_CHRG_MVMNT_PRC;
				    EXCEPTION
					WHEN OTHERS THEN
					    RETURN 'EXCEPTION WHEN INSRT_OTHR_CHRG_MVMNT '||GET_SQLERRM;
				    END;
			       Elsif P_DOC_TYP=149 Then
				    BEGIN
					INSRT_RQ_OTHR_CHRG_MVMNT_PRC;
				    EXCEPTION
					WHEN OTHERS THEN
					    RETURN 'EXCEPTION  WHEN INSRT_OTHR_CHRG_MVMNT '||GET_SQLERRM;
				    END;
			       End If;
		END;

	    END LOOP;
	ELSE
	    FOR SAL_CHRG_C IN (SELECT CHRG.SC_NO,
				     CHRG.SC_NAME,
				     NVL (CHRG.SC_TYPE, 0)     SC_TYPE,
				     CHRG.AMT_TYPE AMT_TYPE,
				     NVL (CHRG.USE_VAT, 0)     USE_VAT,
				     CHRG.CLC_VAT_OTHR_TYP,
				     CHRG.ALLOW_RETURN,
				     CHRG.BILL_DOC_TYPE,
				     CHRG.SC_CST_TYPE,
				     CHRG.SC_WCODE_TYPE,
				     CHRG.A_CODE,
				     CHRG.AC_CODE_DTL,
				     CHRG.AC_DTL_TYP,
				     CHRG.A_CY,
				     CHRG.AC_RATE,
				     NVL (CHRG.AMT, 0)	       AMT
				FROM SALES_CHARGES CHRG
			       WHERE	-- NVL (CHRG.FILL_AUTO, 0) = 1
				      NVL (CHRG.DIFF_CMPNS_QTY_SR, 0) = 0
				     AND NVL (CHRG.INACTIVE, 0) = 0
				     AND NVL (CHRG.INV_ITEM, 0) = 0
				     AND (NVL(USE_IN_POS_FLG,0) = 1 Or NVL(Use_Sc_In_Sho_Sys_Flg,0)=1 )
				     AND NVL (CHRG.SC_TYPE,0) IN(1,2)
				     AND AMT_TYPE IN (0,1)
				     And nvl(Sc_Add_Frc_Invoice,0)<>1
				     AND DECODE(CHRG.BILL_DOC_TYPE,NULL,0,CHRG.BILL_DOC_TYPE) = DECODE(CHRG.BILL_DOC_TYPE,NULL,0,G_BILL_TYPE)
			    ORDER BY SC_NO)
	    LOOP

		DECLARE
		    PROCEDURE INSRT_OTHR_CHRG_MVMNT_PRC
		    IS
		    BEGIN
			INSERT INTO POS_OTHR_CHRG_MVMNT(DOC_TYPE,
						  SC_NO,
						  SC_NM,
						  SC_PRCNT,
						  SC_AMT,
						  A_CY,
						  AC_RATE,
						  RCRD_NO,
						  BILL_NO,
						  BILL_SRL,
						  SC_A_CY,
						  SC_AC_RATE,
						  VAT_AMT,
						  VAT_PRCNT,
						  AD_U_ID,
						  AD_DATE,
						  AD_TRMNL_NM)
					   VALUES(P_DOC_TYP,
						  SAL_CHRG_C.SC_NO,
						  SAL_CHRG_C.SC_NAME,
						  SAL_CHRG_C.AMT,
						  L_SC_AMT,	    --SC_AMT,
						  G_A_CY,
						  G_BILL_RATE,	    --AC_RATE,
						  V_RCRD_NO,
						  G_BILL_NO,
						  G_BILL_SRL,
						  SAL_CHRG_C.A_CY,   --SC_A_CY,
						  SAL_CHRG_C.AC_RATE,--SC_AC_RATE,
						  L_VAT_AMT,
						  L_VAT_PRCNT,
						  G_AD_U_ID,
						  G_AD_DATE,
						  G_AD_TRMNL_NM);
		    EXCEPTION
			WHEN OTHERS THEN
			    RAISE_APPLICATION_ERROR(-20203,'EXCEPTION WHEN INSRT_RQ_OTHR_CHRG_MVMNT_PRC '||GET_SQLERRM);
		    END INSRT_OTHR_CHRG_MVMNT_PRC;
		    PROCEDURE INSRT_RQ_OTHR_CHRG_MVMNT_PRC
		    IS
		    BEGIN
			INSERT INTO POS_RQ_OTHR_CHRG_MVMNT(DOC_TYPE,
						  SC_NO,
						  SC_NM,
						  SC_PRCNT,
						  SC_AMT,
						  A_CY,
						  AC_RATE,
						  RCRD_NO,
						  DOC_NO,
						  DOC_SRL,
						  SC_A_CY,
						  SC_AC_RATE,
						  VAT_AMT,
						  VAT_PRCNT,
						  AD_U_ID,
						  AD_DATE,
						  AD_TRMNL_NM)
					   VALUES(P_DOC_TYP,
						  SAL_CHRG_C.SC_NO,
						  SAL_CHRG_C.SC_NAME,
						  SAL_CHRG_C.AMT,
						  L_SC_AMT,	    --SC_AMT,
						  G_A_CY,
						  G_BILL_RATE,	    --AC_RATE,
						  V_RCRD_NO,
						  G_BILL_NO,
						  G_BILL_SRL,
						  SAL_CHRG_C.A_CY,   --SC_A_CY,
						  SAL_CHRG_C.AC_RATE,--SC_AC_RATE,
						  L_VAT_AMT,
						  L_VAT_PRCNT,
						  G_AD_U_ID,
						  G_AD_DATE,
						  G_AD_TRMNL_NM);
		    EXCEPTION
			WHEN OTHERS THEN
			    RAISE_APPLICATION_ERROR(-20204,'EXCEPTION  WHEN INSRT_RQ_OTHR_CHRG_MVMNT_PRC '||GET_SQLERRM);
		    END INSRT_RQ_OTHR_CHRG_MVMNT_PRC;

		    PROCEDURE CALC_VAT_AMT_OTHR (P_SRVC_AMT NUMBER)
		    IS
		    BEGIN

			IF NVL (YS_TAX_PKG.GET_CLC_TAX_TYP ( G_CLC_TYP_NO_TAX), 0) = 0
			THEN
			    IF G_USE_VAT = 1 AND TO_DATE ( G_BILL_DATE, 'DD/MM/YYYY') >= TO_DATE (G_ACTIVE_VAT_DATE, 'DD/MM/YYYY')
			    THEN
				IF SAL_CHRG_C.SC_NO IS NOT NULL
				THEN
				    BEGIN
					L_VAT_PRCNT := YS_TAX_PKG.GET_INPT_PRCNT(P_CLC_TYP_NO => G_CLC_TYP_NO_TAX, P_INPT_TYP => 1, P_INPT_CODE => SAL_CHRG_C.SC_NO);
				    EXCEPTION
					WHEN OTHERS
					THEN
					    NULL;
				    END;

				    IF NVL (P_SRVC_AMT, 0) > 0 AND L_VAT_PRCNT IS NOT NULL
				    THEN
					L_VAT_AMT := P_SRVC_AMT * L_VAT_PRCNT / 100;
				    ELSE
					L_VAT_PRCNT := NULL;
					L_VAT_AMT := NULL;
				    END IF;
				END IF;
			    END IF;
			ELSE
			    L_VAT_PRCNT := 0;
			    L_VAT_AMT := NULL;
			END IF;
		    END CALC_VAT_AMT_OTHR;

		BEGIN
		    IF SAL_CHRG_C.AMT_TYPE = 1 THEN -- 0-PRCNT 1-AMT
			IF NVL(G_BILL_AMT,0) > 0 THEN
			    IF G_USE_PRICE_INCLUDE_VAT = 1 THEN
				L_SC_AMT := ((NVL(SAL_CHRG_C.AMT,0) * 100) / (NVL(YS_TAX_PKG.GET_INPT_PRCNT (G_CLC_TYP_NO_TAX,1,SAL_CHRG_C.SC_NO),0) + 100));
			    ELSE
				L_SC_AMT := NVL(SAL_CHRG_C.AMT,0);
			    END IF;  	 	
			ELSE
			   L_SC_AMT := 0;
			END IF;
		    ELSE
			L_SC_AMT := NVL(G_BILL_AMT,0) * NVL(SAL_CHRG_C.AMT,0)/100;
		    END IF;

		    IF SAL_CHRG_C.SC_TYPE = 2 THEN
			L_SC_AMT := L_SC_AMT * -1;	
		    END IF;

		    IF SAL_CHRG_C.SC_NO IS NOT NULL AND L_SC_AMT <> 0 AND G_USE_VAT = 1
		    THEN
			V_RCRD_NO := V_RCRD_NO + 1;
			CALC_VAT_AMT_OTHR (L_SC_AMT);
		    ELSE
			L_VAT_PRCNT := 0;
			L_VAT_AMT := NULL;
		    END IF;
		    IF P_DOC_TYP=4 THEN
				    BEGIN
					INSRT_OTHR_CHRG_MVMNT_PRC;
				    EXCEPTION
					WHEN OTHERS THEN
					    RETURN 'EXCEPTION WHEN INSRT_OTHR_CHRG_MVMNT_PRC '||GET_SQLERRM;
				    END;
			 ELSIF P_DOC_TYP=149 THEN
					  BEGIN
					INSRT_RQ_OTHR_CHRG_MVMNT_PRC;
				    EXCEPTION
					WHEN OTHERS THEN
					    RETURN 'EXCEPTION WHEN INSRT_OTHR_CHRG_MVMNT_PRC '||GET_SQLERRM;
				    END;
			 END IF;
		END;
	    END LOOP;
	END IF;

	IF P_DOC_TYP=4 Then
	  V_TBL_MST_NM	 :='IAS_POS_BILL_MST';
	  V_TBL_DTL_NM	 :='IAS_POS_BILL_DTL';
	  V_P_FLD_DOC_SER:='BILL_SRL';
	  V_FLD_DOC_AMT  :='BILL_AMT';
	  V_FLD_DOC_SER_INPT :='M.BILL_SRL';
	  V_TBL_INPT_NM  :='POS_OTHR_CHRG_MVMNT';
	  BEGIN
	    SELECT NVL(SUM(SC_AMT), 0), NVL(SUM(VAT_AMT), 0)
	      INTO L_OTHR_AMT, L_VAT_AMT_OTHR
	      FROM POS_OTHR_CHRG_MVMNT
	     WHERE DOC_TYPE=P_DOC_TYP AND BILL_SRL = G_BILL_SRL;
	  EXCEPTION   WHEN OTHERS THEN
		L_OTHR_AMT     := 0;
		L_VAT_AMT_OTHR := 0;
	  END;
	Elsif P_DOC_TYP=149 Then
	  V_TBL_MST_NM	 :='SALES_ORDER';
	  V_TBL_DTL_NM	 :='ORDER_DETAIL';
	  V_P_FLD_DOC_SER:='ORDER_NO';
	  V_FLD_DOC_AMT  :='ORDER_AMT';
	  V_FLD_DOC_SER_INPT :='M.DOC_SRL';
	  V_TBL_INPT_NM  :='POS_RQ_OTHR_CHRG_MVMNT';
	  BEGIN
	    SELECT NVL(SUM(SC_AMT), 0), NVL(SUM(VAT_AMT), 0)
	      INTO L_OTHR_AMT, L_VAT_AMT_OTHR
	      FROM POS_RQ_OTHR_CHRG_MVMNT
	     WHERE DOC_TYPE=P_DOC_TYP AND DOC_SRL=G_BILL_SRL;
	  EXCEPTION WHEN OTHERS THEN
		L_OTHR_AMT     := 0;
		L_VAT_AMT_OTHR := 0;
	  END;
	End If;
	IF L_OTHR_AMT > 0 THEN
	    YS_TAX_PKG.CLC_INPT_TAX_AFTR_SAVE( P_CLC_TYP_NO	    => G_CLC_TYP_NO_TAX,
					       P_DOC_TYP	    => P_DOC_TYP, -- Doc_Type In  Ias_Sys.Ias_Docjv_Type_Systems
					       P_DOC_NO 	    => G_BILL_NO,
					       P_DOC_SER	    => G_BILL_SRL,
					       P_BILL_DOC_TYP	    => G_BILL_TYPE,
					       P_DOC_JV_TYP	    => G_SI_TYPE,
					       P_DOC_DATE	    => G_BILL_DATE,
					       P_A_CY		    => G_A_CY,
					       P_AC_RATE	    => G_BILL_RATE,
					       P_TBL_INPT_NM	    => V_TBL_INPT_NM,
					       P_TBL_MST_NM	    => V_TBL_MST_NM,
					       P_TBL_DTL_NM	    => V_TBL_DTL_NM,
					       P_FLD_DOC_SER	    => V_P_FLD_DOC_SER,
					       P_FLD_DOC_AMT	    => V_FLD_DOC_AMT,
					       P_FLD_DOC_SER_INPT   => V_FLD_DOC_SER_INPT,
					       P_FLD_TAX_A_CODE     => 'TD.AC_CODE_AR',
					       P_INPT_TYP	    => 1,
					       P_FLD_INPT_CODE	    => 'M.SC_NO',
					       P_FLD_INPT_AMT	    => 'M.SC_AMT',
					       P_FLD_DOC_SEQ	    => NULL,
					       P_CLC_DOC_TYP	    => 1, -- CLC_DOC_TYP  1= SALES ,2 = PURCHASE ,
					       P_DR_CR_FLG	    => -1,
					       P_LNG_NO 	    => 1);
	END IF;

	IF P_DOC_TYP=4 THEN
			UPDATE IAS_POS_BILL_MST
			   SET OTHR_AMT = NVL(L_OTHR_AMT, 0),
			       VAT_AMT_OTHR = NVL(L_VAT_AMT_OTHR, 0)
			 WHERE BILL_SRL = G_BILL_SRL;
		
			UPDATE IAS_POS_BILL_DTL
			   SET OTHR_AMT = DECODE(NVL(I_QTY,0)*NVL(I_PRICE,0),0,0,(NVL (L_OTHR_AMT, 0) / (G_BILL_AMT)) * (NVL(I_PRICE,0))),
			       VAT_AMT_OTHR = DECODE(NVL(I_QTY,0)*NVL(I_PRICE,0),0,0,(NVL (L_VAT_AMT_OTHR, 0) / (G_BILL_AMT)) * (NVL(I_PRICE,0)))
			 WHERE BILL_SRL = G_BILL_SRL;
       ELSIF P_DOC_TYP=149 THEN
		  BEGIN
		   UPDATE SALES_ORDER
		   SET OTHR_AMT = NVL(L_OTHR_AMT, 0),
		       VAT_AMT_OTHR =NVL(L_VAT_AMT_OTHR,0)
		    WHERE ORDER_SER  =G_BILL_SRL;
	
		   UPDATE ORDER_DETAIL
		    SET OTHR_AMT = DECODE(NVL(I_QTY,0)*NVL(I_PRICE,0),0,0,(NVL (L_OTHR_AMT, 0) / (G_BILL_AMT)) * (NVL(I_PRICE,0))),
			VAT_AMT_OTHR =DECODE(NVL(I_QTY,0)*NVL(I_PRICE,0),0,0,(NVL (L_VAT_AMT_OTHR, 0) / (G_BILL_AMT)) * (NVL(I_PRICE,0)))
			WHERE ORDER_SER = G_BILL_SRL;
		 EXCEPTION WHEN OTHERS THEN
		    NULL;
		 END;
       END IF;
	RETURN NULL;
  EXCEPTION
	WHEN OTHERS THEN
	    RETURN 'EXCEPTION IN INSRT_OTHR_CHRG_MVMNT	'||GET_SQLERRM;
  END INSRT_OTHR_CHRG_MVMNT;
  --#----------------------------------------------------------------------------------------------------------#--
BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_DATE_FORMAT=''DD/MM/YYYY''';
END POS_OTHR_CHRG_PKG;
/
