-- =============================================
-- PACKAGE SPEC: IAS_CMP_PKG  (status: INVALID)
-- =============================================
CREATE OR REPLACE
PACKAGE IAS_CMP_PKG
AS
    FUNCTION GET_TAX_GRP_NO(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION GET_TAX_CODE(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN VARCHAR2;

    FUNCTION GET_TAX_CUR(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN VARCHAR2;

    FUNCTION IS_CMP_USE_E_INVOICE(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION IS_CMP_SHW_QR_CODE_RPRT(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION NO_OF_TAX_COLL_ENTITIES(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION NO_DCML_TOT_INVOC_B4_AFTR_TAX(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION NO_DCML_NET_AMT_PER_ITM(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION NO_DCML_ALL_DISC_AMT_FLDS(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION NO_DCML_NET_TAX_PER_INVOC(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION NO_DCML_TAX_PER_DISC_CHRG(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION NO_DCML_DISC_PRC_IN_INVOC_ITMS(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION MAX_DAYS_BTWN_INVOC_OUTGOING(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION MAX_DAYS_BTWN_INVOC_INVOC_OUT(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION IS_CMP_USE_TAX_DUE_DATE(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION GET_SCTR_NO(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION MAX_DYS_BTWN_TAX_DUEDATE_INVOC(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION MIN_AMT_NET_INVOC_TAX(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION ALLW_CUM_INVOC_SUP_DIF_TAX_PRD(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION ALLW_PART_INVOC_ORDER_CNTRCT(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION ALLW_INVOC_IN_NOTE_DIF_TAX_PRD(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION GET_MAIN_L_LANG_NO(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION GET_MAIN_L_LANG_CODE(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN VARCHAR2;

    FUNCTION GET_F_LANG_NO(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION GET_F_LANG_CODE(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN VARCHAR2;

    FUNCTION GET_MAX_FREE_INVOC_ITM_SRVC(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

    FUNCTION GET_MAX_FREE_INVOC_CUST(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER;

END IAS_CMP_PKG;
/

-- ---------------------------------------------
-- PACKAGE BODY: IAS_CMP_PKG  (status: INVALID)
-- ---------------------------------------------
CREATE OR REPLACE
PACKAGE BODY IAS_CMP_PKG
AS
    FUNCTION GET_TAX_GRP_NO(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP     NUMBER;
	V_TAX_GRP_NO   NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT TAX_GRP_NO
	  INTO V_TAX_GRP_NO
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_TAX_GRP_NO);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END GET_TAX_GRP_NO;

    FUNCTION GET_TAX_CODE(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN VARCHAR2
    IS
	V_MAIN_CMP   NUMBER;
	V_TAX_CODE   VARCHAR2(20);
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT TAX_CODE
	  INTO V_TAX_CODE
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_TAX_CODE);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END GET_TAX_CODE;

    FUNCTION GET_TAX_CUR(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN VARCHAR2
    IS
	V_MAIN_CMP   NUMBER;
	V_TAX_CUR    VARCHAR2(200);
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT TAX_CUR
	  INTO V_TAX_CUR
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_TAX_CUR);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END GET_TAX_CUR;

    FUNCTION IS_CMP_USE_E_INVOICE(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP	  NUMBER;
	V_USE_E_INVOICE   NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT NVL(USE_E_INVOICE, 0)
	  INTO V_USE_E_INVOICE
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_USE_E_INVOICE);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END IS_CMP_USE_E_INVOICE;

    FUNCTION IS_CMP_SHW_QR_CODE_RPRT(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP		 NUMBER;
	V_SHW_QR_CODE_RPRT_FLG	 NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT NVL(SHW_QR_CODE_RPRT_FLG, 0)
	  INTO V_SHW_QR_CODE_RPRT_FLG
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_SHW_QR_CODE_RPRT_FLG);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END IS_CMP_SHW_QR_CODE_RPRT;

    FUNCTION NO_OF_TAX_COLL_ENTITIES(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP		    NUMBER;
	V_NO_OF_TAX_COLL_ENTITIES   NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT NO_OF_TAX_COLL_ENTITIES
	  INTO V_NO_OF_TAX_COLL_ENTITIES
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_NO_OF_TAX_COLL_ENTITIES);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END NO_OF_TAX_COLL_ENTITIES;

    FUNCTION NO_DCML_TOT_INVOC_B4_AFTR_TAX(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP   NUMBER;
	V_NO_DCML    NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT NO_DCML_TOT_INVOC_B4_AFTR_TAX
	  INTO V_NO_DCML
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_NO_DCML);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END NO_DCML_TOT_INVOC_B4_AFTR_TAX;

    FUNCTION NO_DCML_NET_AMT_PER_ITM(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP   NUMBER;
	V_NO_DCML    NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT NO_DCML_NET_AMT_PER_ITM
	  INTO V_NO_DCML
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_NO_DCML);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END NO_DCML_NET_AMT_PER_ITM;

    FUNCTION NO_DCML_ALL_DISC_AMT_FLDS(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP   NUMBER;
	V_NO_DCML    NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT NO_DCML_ALL_DISC_AMT_FLDS
	  INTO V_NO_DCML
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_NO_DCML);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END NO_DCML_ALL_DISC_AMT_FLDS;

    FUNCTION NO_DCML_NET_TAX_PER_INVOC(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP   NUMBER;
	V_NO_DCML    NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT NO_DCML_NET_TAX_PER_INVOC
	  INTO V_NO_DCML
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_NO_DCML);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END NO_DCML_NET_TAX_PER_INVOC;

    FUNCTION NO_DCML_TAX_PER_DISC_CHRG(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP   NUMBER;
	V_NO_DCML    NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT NO_DCML_TAX_PER_DISC_CHRG
	  INTO V_NO_DCML
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_NO_DCML);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END NO_DCML_TAX_PER_DISC_CHRG;

    FUNCTION NO_DCML_DISC_PRC_IN_INVOC_ITMS(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP   NUMBER;
	V_NO_DCML    NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT NO_DCML_DISC_PRC_IN_INVOC_ITMS
	  INTO V_NO_DCML
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_NO_DCML);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END NO_DCML_DISC_PRC_IN_INVOC_ITMS;

    FUNCTION MAX_DAYS_BTWN_INVOC_OUTGOING(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP   NUMBER;
	V_MAX_DAYS   NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT MAX_DAYS_BTWN_INVOC_OUTGOING
	  INTO V_MAX_DAYS
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_MAX_DAYS);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END MAX_DAYS_BTWN_INVOC_OUTGOING;

    FUNCTION MAX_DAYS_BTWN_INVOC_INVOC_OUT(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP   NUMBER;
	V_MAX_DAYS   NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT MAX_DAYS_BTWN_INVOC_INVOC_OUT
	  INTO V_MAX_DAYS
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_MAX_DAYS);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END MAX_DAYS_BTWN_INVOC_INVOC_OUT;

    FUNCTION IS_CMP_USE_TAX_DUE_DATE(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP	     NUMBER;
	V_USE_TAX_DUE_DATE   NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT NVL(USE_TAX_DUE_DATE, 0)
	  INTO V_USE_TAX_DUE_DATE
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_USE_TAX_DUE_DATE);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END IS_CMP_USE_TAX_DUE_DATE;

    FUNCTION GET_SCTR_NO(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP   NUMBER;
	V_SCTR_NO    NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT SCTR_NO
	  INTO V_SCTR_NO
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_SCTR_NO);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END GET_SCTR_NO;

    FUNCTION MAX_DYS_BTWN_TAX_DUEDATE_INVOC(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP   NUMBER;
	V_MAX_DYS    NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT MAX_DYS_BTWN_TAX_DUEDATE_INVOC
	  INTO V_MAX_DYS
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_MAX_DYS);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END MAX_DYS_BTWN_TAX_DUEDATE_INVOC;

    FUNCTION MIN_AMT_NET_INVOC_TAX(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP   NUMBER;
	V_MIN_AMT    NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT MIN_AMT_NET_INVOC_TAX
	  INTO V_MIN_AMT
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_MIN_AMT);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END MIN_AMT_NET_INVOC_TAX;

    FUNCTION ALLW_CUM_INVOC_SUP_DIF_TAX_PRD(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP   NUMBER;
	V_CNT	     NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT NVL(ALLW_CUM_INVOC_SUP_DIF_TAX_PRD, 0)
	  INTO V_CNT
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_CNT);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END ALLW_CUM_INVOC_SUP_DIF_TAX_PRD;


    FUNCTION ALLW_PART_INVOC_ORDER_CNTRCT(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP   NUMBER;
	V_CNT	     NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT NVL(ALLW_PART_INVOC_ORDER_CNTRCT, 0)
	  INTO V_CNT
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_CNT);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END ALLW_PART_INVOC_ORDER_CNTRCT;


    FUNCTION ALLW_INVOC_IN_NOTE_DIF_TAX_PRD(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP   NUMBER;
	V_CNT	     NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT NVL(ALLW_INVOC_IN_NOTE_DIF_TAX_PRD, 0)
	  INTO V_CNT
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_CNT);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END ALLW_INVOC_IN_NOTE_DIF_TAX_PRD;

    FUNCTION GET_MAIN_L_LANG_NO(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP	   NUMBER;
	V_MAIN_L_LANG_NO   NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT MAIN_L_LANG_NO
	  INTO V_MAIN_L_LANG_NO
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_MAIN_L_LANG_NO);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END GET_MAIN_L_LANG_NO;

    FUNCTION GET_MAIN_L_LANG_CODE(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN VARCHAR2
    IS
	V_MAIN_CMP	     NUMBER;
	V_MAIN_L_LANG_CODE   VARCHAR2(200);
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT MAIN_L_LANG_CODE
	  INTO V_MAIN_L_LANG_CODE
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_MAIN_L_LANG_CODE);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END GET_MAIN_L_LANG_CODE;

    FUNCTION GET_F_LANG_NO(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP    NUMBER;
	V_F_LANG_NO   NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT F_LANG_NO
	  INTO V_F_LANG_NO
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_F_LANG_NO);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END GET_F_LANG_NO;

    FUNCTION GET_F_LANG_CODE(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN VARCHAR2
    IS
	V_MAIN_CMP	NUMBER;
	V_F_LANG_CODE	VARCHAR2(200);
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT F_LANG_CODE
	  INTO V_F_LANG_CODE
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_F_LANG_CODE);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END GET_F_LANG_CODE;

    FUNCTION GET_MAX_FREE_INVOC_ITM_SRVC(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP		    NUMBER;
	V_MAX_FREE_INVOC_ITM_SRVC   NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT MAX_FREE_INVOC_ITM_SRVC
	  INTO V_MAX_FREE_INVOC_ITM_SRVC
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_MAX_FREE_INVOC_ITM_SRVC);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END GET_MAX_FREE_INVOC_ITM_SRVC;

    FUNCTION GET_MAX_FREE_INVOC_CUST(P_BRN_NO IN S_BRN.BRN_NO%TYPE)
	RETURN NUMBER
    IS
	V_MAIN_CMP		NUMBER;
	V_MAX_FREE_INVOC_CUST	NUMBER;
    BEGIN

	V_MAIN_CMP := IAS_BRN_PKG.GET_BRN_MAIN_CMP(P_BRN_NO => P_BRN_NO);

	SELECT MAX_FREE_INVOC_CUST
	  INTO V_MAX_FREE_INVOC_CUST
	  FROM S_CMPNY
	 WHERE CMP_NO = V_MAIN_CMP AND ROWNUM <= 1;

	RETURN (V_MAX_FREE_INVOC_CUST);
    EXCEPTION
	WHEN OTHERS THEN
	    RETURN (NULL);
    END GET_MAX_FREE_INVOC_CUST;

END IAS_CMP_PKG;
/
