-- =============================================
-- PACKAGE SPEC: POS_HOTEL_PRIMO_PKG  (status: VALID)
-- =============================================
CREATE OR REPLACE
PACKAGE POS_HOTEL_PRIMO_PKG
IS
    FUNCTION ADD_SRVC_CHRG(P_BRN_NO	   NUMBER,
			   P_BILL_NO	   NUMBER,
			   P_BILL_SRL	   NUMBER,
			   P_RT_BILL_NO    NUMBER DEFAULT NULL,
			   P_RT_BILL_SRL   NUMBER DEFAULT NULL,
			   P_A_CY	   VARCHAR2,
			   P_BILL_RATE	   NUMBER,
			   P_BILL_AMT	   NUMBER,
			   P_ROOM_NO	   VARCHAR2,
			   P_YEAR_NO	   NUMBER,
			   P_WEB_SRVC_IP   VARCHAR2,
			   P_AD_TRMNL_NM   VARCHAR2 DEFAULT NULL,
			   P_DOC_TYP	   NUMBER DEFAULT 1)--##1-BILL 2- RETURN BILL
	RETURN VARCHAR2;
    FUNCTION GET_OCCPD_ROOMS(P_WEB_SRVC_URL VARCHAR2)
	RETURN CLOB;
END POS_HOTEL_PRIMO_PKG;
/

-- ---------------------------------------------
-- PACKAGE BODY: POS_HOTEL_PRIMO_PKG  (status: VALID)
-- ---------------------------------------------
CREATE OR REPLACE
PACKAGE BODY POS_HOTEL_PRIMO_PKG
IS
    FUNCTION ADD_SRVC_CHRG(P_BRN_NO	   NUMBER,
			   P_BILL_NO	   NUMBER,
			   P_BILL_SRL	   NUMBER,
			   P_RT_BILL_NO    NUMBER DEFAULT NULL,
			   P_RT_BILL_SRL   NUMBER DEFAULT NULL,
			   P_A_CY	   VARCHAR2,
			   P_BILL_RATE	   NUMBER,
			   P_BILL_AMT	   NUMBER,
			   P_ROOM_NO	   VARCHAR2,
			   P_YEAR_NO	   NUMBER,
			   P_WEB_SRVC_IP   VARCHAR2,
			   P_AD_TRMNL_NM   VARCHAR2 DEFAULT NULL,
			   P_DOC_TYP	   NUMBER DEFAULT 1)--##1-BILL 2- RETURN BILL
	RETURN VARCHAR2
    IS
	REQ		   UTL_HTTP.REQ;
	RESP		   UTL_HTTP.RESP;
	L_RSLT		   VARCHAR2(500);
	L_SRVC_NM	   VARCHAR2(100) := (CASE NVL(P_DOC_TYP,1) WHEN 2 THEN 'POS_RTRN_BILL' ELSE 'POS_BILL' END);
	L_BUFFER_SIZE	   NUMBER(10) := 512;
	L_LINE_SIZE	   NUMBER(10) := 50;
	L_LINES_COUNT	   NUMBER(10) := 20;
	L_STRING_REQUEST   VARCHAR2(512);
	L_LINE		   VARCHAR2(128);
	L_SUBSTRING_MSG    VARCHAR2(512);
	L_RAW_DATA	   RAW(1024);
	L_URL		   VARCHAR2(4000);
	L_SRVC_PATH	   VARCHAR2(4000) := NVL(P_WEB_SRVC_IP, 'localhost') || '/WebRestSys/Service1.svc/';
	L_METHOD	   VARCHAR2(20) := 'POST';
	NAME		   VARCHAR2(4000);
	BUFFER		   VARCHAR2(10000) := '';
	L_CONTENT	   VARCHAR2(32000);
	L_RES_NO	   NUMBER;
	L_CUR_NO	   NUMBER;

	FUNCTION GET_JSON_VAL(P_KEY VARCHAR2)
	    RETURN VARCHAR2
	IS
	    L_KEY_VAL	VARCHAR2(4000);
	BEGIN

	    SELECT VALUE
	      INTO L_KEY_VAL
	      FROM (WITH
			SRC AS(SELECT REPLACE(BUFFER, '{', '{,') IN_STR FROM DUAL),
			DATA (RES, STR, ORIG_STR, P)
			AS
			    (SELECT 'NULL' RES,
				    IN_STR STR,
				    IN_STR ORIG_STR,
				    1 P
			       FROM DUAL CROSS JOIN SRC
			     UNION ALL
			     SELECT REGEXP_SUBSTR(STR, '[^,]+') RES,
				    SUBSTR(STR, INSTR(STR, ',') + 1) STR,
				    ORIG_STR,
				    P + 1
			       FROM DATA
			      WHERE P <= REGEXP_COUNT(ORIG_STR, '[,]') + 1),
			COMPONENTS
			AS
			    (SELECT REGEXP_REPLACE(RES, '[{"}]') RES
			       FROM DATA
			      WHERE RES <> 'NULL')
		    SELECT REGEXP_SUBSTR(RES,
					 '[^:]+',
					 1,
					 1)
			       KEY,
			   REGEXP_SUBSTR(RES,
					 '[^:]+',
					 1,
					 2)
			       VALUE
		      FROM COMPONENTS)
	     WHERE INSTR(UPPER(KEY) , P_KEY)  >  0 ;

	    RETURN L_KEY_VAL;
	EXCEPTION
	    WHEN NO_DATA_FOUND THEN
		RETURN NULL;
	    WHEN OTHERS THEN
		RETURN NULL;
	END GET_JSON_VAL;

	PROCEDURE CALL_WEB_SRVC
	IS
	BEGIN
	    REQ := UTL_HTTP.BEGIN_REQUEST(L_URL, L_METHOD, ' HTTP/1.1');

	    IF L_METHOD = 'POST' THEN
		UTL_HTTP.SET_HEADER(REQ, 'content-type', 'application/json;charset=UTF-8');

		L_CONTENT := CONVERT(L_CONTENT, 'AL32UTF8');
		UTL_HTTP.SET_BODY_CHARSET('UTF-8');

		UTL_HTTP.SET_HEADER(R => REQ, NAME => 'Content-Length', VALUE => LENGTHB(L_CONTENT));

	       <<REQUEST_LOOP>>

		FOR I IN 0 .. CEIL(LENGTH(L_CONTENT) / L_BUFFER_SIZE) - 1
		LOOP
		    L_SUBSTRING_MSG := SUBSTR(L_CONTENT, I * L_BUFFER_SIZE + 1, L_BUFFER_SIZE);

		    BEGIN
			L_RAW_DATA := UTL_RAW.CAST_TO_RAW(L_CONTENT);
			UTL_HTTP.WRITE_RAW(R => REQ, DATA => L_RAW_DATA);
		    EXCEPTION
			WHEN NO_DATA_FOUND THEN
			    EXIT REQUEST_LOOP;
		    END;

		END LOOP REQUEST_LOOP;

	    END IF;

	    RESP := UTL_HTTP.GET_RESPONSE(REQ);

	    BEGIN

		IF RESP.STATUS_CODE = 200 THEN
		    UTL_HTTP.READ_LINE(RESP, BUFFER);

		    IF GET_JSON_VAL(P_KEY => '_ERRNO') = '0' THEN
			L_RSLT := 0;
		    ELSE
			L_RSLT := GET_JSON_VAL(P_KEY => '_ERRMSG');
		    END IF;
		ELSE
		    L_RSLT := 'ERROR IN REQUEST ,Response Code : ' || RESP.STATUS_CODE;
		END IF;

		UTL_HTTP.END_RESPONSE(RESP);
	    EXCEPTION
		WHEN UTL_HTTP.END_OF_BODY THEN
		    UTL_HTTP.END_RESPONSE(RESP);
		    L_RSLT := '-3 : ' || SQLERRM;
	    END;

	END CALL_WEB_SRVC;

	PROCEDURE GET_RES_NO
	IS
	BEGIN
	    L_URL := L_SRVC_PATH || 'GetOccupiedRoomsNo?Room_no=' || P_ROOM_NO;
	    L_METHOD := 'GET';

	    CALL_WEB_SRVC;

	    L_RES_NO := GET_JSON_VAL(P_KEY => 'RES_NO');
	END GET_RES_NO;
    BEGIN

	/*BEGIN
	    SELECT CUR_NO
	      INTO L_CUR_NO
	      FROM EX_RATE
	     WHERE CUR_CODE = P_A_CY
	       AND ROWNUM <= 1;
	EXCEPTION
	    WHEN OTHERS THEN
		L_CUR_NO := 1;
	END;*/

	GET_RES_NO;

	L_URL := L_SRVC_PATH || (CASE NVL(P_DOC_TYP,1) WHEN 2 THEN 'AddReturnService' ELSE 'AddServiceCharg' END);
	L_METHOD := 'POST';

	L_CONTENT :=
	    '{
		"Amount": "' || ROUND(NVL(P_BILL_AMT, 0),15) || '",
		"Service_No": "4",
		"Amount_Type":"1",
		"Curr_Change": "' || ROUND(P_BILL_RATE,15) || '",
		"Curr_Code": "' || P_A_CY || '",
		"Res_No": "' || L_RES_NO || '",
		"Room_No": "' || P_ROOM_NO || '",
		"S_Date": "' || TO_CHAR(SYSDATE, 'yyyy-MM-dd') || '",
		"Service_Name": "'||L_SRVC_NM||'",
		"RestBranch_No":"' || P_BRN_NO || '",
		"Hotel_No":"1",
		"Brn_No":"' || P_BRN_NO ||'",
		"Year_No":"' || P_YEAR_NO || '",
		"Ad_Trmnl_Nm":"' || P_AD_TRMNL_NM || '",
		"Aserial": "' || (CASE NVL(P_DOC_TYP,1) WHEN 2 THEN P_RT_BILL_NO ELSE P_BILL_NO END) || '",
		' || (CASE NVL(P_DOC_TYP,1) WHEN 2 THEN '"BillNo": "' ||P_BILL_NO|| '",' ELSE NULL END)||'
		"Source":"Onyx POS System"
	     }';

	CALL_WEB_SRVC;

	RETURN L_RSLT;
    EXCEPTION
	WHEN OTHERS THEN
	    UTL_HTTP.END_RESPONSE(RESP);
	    RETURN '-4 : ' || SQLERRM;
    END ADD_SRVC_CHRG;

    FUNCTION GET_OCCPD_ROOMS(P_WEB_SRVC_URL VARCHAR2)
	RETURN CLOB
    IS
	L_REQ		    UTL_HTTP.REQ;
	L_RES		    UTL_HTTP.RESP;
	L_CONTENT_IN_RAW    RAW(32767);
	L_CURRENT_CHARS     INTEGER;
	L_CHARS_PER_CHUNK   NUMBER;
	L_CLOB_OFFSET	    NUMBER;
	L_CONTENT_LENGTH    NUMBER;
	L_CLOB_LENGTH	    NUMBER;
	L_CHUNK_STRING	    VARCHAR2(32767);
	L_RES_TEXT	    CLOB;
	L_HTTP_RES_CODE     NUMBER;
	L_SRVR_WEB_SRVC     VARCHAR2(100);
	L_APPLICATIONID     VARCHAR2(500);
	L_SENDERID	    NUMBER;
	L_URL		    VARCHAR2(4000);
	BUFFER		    VARCHAR2(4000);

	L_CONTENT	    VARCHAR2(4000);
    BEGIN

	IF P_WEB_SRVC_URL IS NULL THEN
	    BEGIN
		SELECT HTL_SYS_WEB_SRVC_IP
		  INTO L_URL
		  FROM IAS_PARA_POS;
	    EXCEPTION
		WHEN OTHERS THEN
		    L_URL := 'localhost';
	    END;
	END IF;

	L_URL := NVL(NVL(P_WEB_SRVC_URL,L_URL), 'localhost') || '/WebRestSys/Service1.svc//GetOccupiedRooms';
	L_CONTENT := '';

	IF L_URL IS NULL OR L_URL = NULL THEN
	    RAISE_APPLICATION_ERROR(-20001, 'URL can not be empty');
	END IF;

	L_REQ := UTL_HTTP.BEGIN_REQUEST(L_URL, 'GET', UTL_HTTP.HTTP_VERSION_1_1);
	UTL_HTTP.SET_HEADER(L_REQ, 'content-type', 'application/json; charset=utf-8');

	UTL_HTTP.SET_HEADER(L_REQ, 'user-agent', 'mozilla/4.0');
	UTL_HTTP.SET_BODY_CHARSET(L_REQ, 'UTF-8');
	UTL_HTTP.SET_HEADER(L_REQ, 'Transfer-Encoding', 'chunked');

	L_CLOB_LENGTH := DBMS_LOB.GETLENGTH(L_CONTENT);
	L_CHARS_PER_CHUNK := FLOOR(32767 / 4);

	L_CLOB_OFFSET := 1;
	L_CONTENT_LENGTH := 0;
	L_CLOB_OFFSET := 1;

	BEGIN
	    WHILE L_CLOB_OFFSET <= L_CLOB_LENGTH
	    LOOP
		L_CURRENT_CHARS := L_CHARS_PER_CHUNK;
		DBMS_LOB.READ(L_CONTENT,
			      L_CURRENT_CHARS,
			      L_CLOB_OFFSET,
			      L_CHUNK_STRING);
		EXIT WHEN L_CURRENT_CHARS < 1;

		UTL_HTTP.WRITE_TEXT(L_REQ, L_CHUNK_STRING);
		L_CLOB_OFFSET := L_CLOB_OFFSET + L_CURRENT_CHARS;
	    END LOOP;
	EXCEPTION
	    WHEN NO_DATA_FOUND THEN
		NULL;
	END;

	L_RES := UTL_HTTP.GET_RESPONSE(L_REQ);

	UTL_HTTP.READ_TEXT(L_RES, L_RES_TEXT);
	L_HTTP_RES_CODE := L_RES.STATUS_CODE;
	UTL_HTTP.END_RESPONSE(L_RES);

	IF L_HTTP_RES_CODE <> 200 THEN
	    RETURN L_RES_TEXT;
	    --RETURN NULL;
	ELSE
	    RETURN L_RES_TEXT;
	END IF;
    EXCEPTION
	WHEN UTL_HTTP.END_OF_BODY THEN
	    UTL_HTTP.END_REQUEST(L_REQ);
	    UTL_HTTP.END_RESPONSE(L_RES);
	    --RAISE;
	WHEN OTHERS THEN
	    UTL_HTTP.END_REQUEST(L_REQ);
	    UTL_HTTP.END_RESPONSE(L_RES);
	    RAISE;
    END GET_OCCPD_ROOMS;
END POS_HOTEL_PRIMO_PKG;
/
