-- PROCEDURE: UPDT_ITM_TAX_TRNS_INFO (status: INVALID)
CREATE OR REPLACE
PROCEDURE UPDT_ITM_TAX_TRNS_INFO (P_BRN_YR IN NUMBER ) IS
  CURSOR C_ITM IS
   SELECT I_CODE , TAX_NO , AGNCY_NO , TAX_PRCNT , TAX_TYP_CODE , VAT_CAT_CODE
    FROM  GNR_TAX_ITM	ITM    ;
   TYPE FETCH_ARRAY IS TABLE OF C_ITM%ROWTYPE ;
    S_ARRAY FETCH_ARRAY;
 BEGIN
    OPEN C_ITM ;
    LOOP
	 FETCH C_ITM BULK COLLECT INTO S_ARRAY	; --LIMIT 20000
	 FORALL I IN 1..S_ARRAY.COUNT
		 UPDATE POS_TAX_ITM_MOVMNT   MOVMNT
		 SET  MOVMNT.TAX_TYP_CODE     = S_ARRAY(I).TAX_TYP_CODE ,
		      MOVMNT.ITM_VAT_CAT_CODE = S_ARRAY(I).VAT_CAT_CODE
		 WHERE MOVMNT.BRN_YEAR	= P_BRN_YR
		   AND MOVMNT.TAX_NO	= S_ARRAY(I).TAX_NO
		   AND MOVMNT.AGNCY_NO	= S_ARRAY(I).AGNCY_NO
		   AND MOVMNT.TAX_PRCNT = S_ARRAY(I).TAX_PRCNT
		   AND ITM_VAT_CAT_CODE IS NULL  ;
	       COMMIT;
	       EXIT WHEN C_ITM%NOTFOUND;
    END LOOP;
    CLOSE C_ITM ;
 END UPDT_ITM_TAX_TRNS_INFO ;
/
