-- PROCEDURE: UPDT_BILL_SRL_IN_RTHST_INFO (status: VALID)
CREATE OR REPLACE
PROCEDURE UPDT_BILL_SRL_IN_RTHST_INFO (P_BRN_YR IN NUMBER ) IS
   CURSOR C_ITM IS
	SELECT RT_BILL.ROWID,
	       BILL.BILL_NO,
	       BILL.BILL_SRL,
	       RT_BILL.RT_BILL_NO
	  FROM IAS_POS_HST_BILL_MST BILL, IAS_POS_HST_RT_BILL_MST RT_BILL
	 WHERE RT_BILL.BRN_YEAR = P_BRN_YR AND
	       BILL.BILL_NO = RT_BILL.BILL_NO
	   AND BILL.BILL_SRL IS NOT NULL
	   AND RT_BILL.BILL_NO IS NOT NULL
	   AND RT_BILL.BILL_SRL IS NULL;

    TYPE FETCH_ARRAY IS TABLE OF C_ITM%ROWTYPE;
    S_ARRAY   FETCH_ARRAY;
BEGIN
    OPEN C_ITM;
    LOOP
	FETCH C_ITM BULK COLLECT INTO S_ARRAY LIMIT 1000;

	FORALL I IN 1 .. S_ARRAY.COUNT
	    UPDATE IAS_POS_HST_RT_BILL_MST RT
	       SET RT.BILL_SRL = S_ARRAY(I).BILL_SRL
	     WHERE ROWID = S_ARRAY(I).ROWID AND RT.BILL_SRL IS NULL;
	COMMIT;
	EXIT WHEN C_ITM%NOTFOUND;
    END LOOP;

    CLOSE C_ITM;
 END UPDT_BILL_SRL_IN_RTHST_INFO;
/
